### ISSUE TITLE
WF simulator bugs?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#105]
I'm trying to find a nice WF simulation to use as an example. In so doing, I've found a number of weirdnesses. For example, the one discussed in https://github.com/tskit-dev/what-is-an-arg-paper/issues/82#issuecomment-1038121481. Here's another (because I think that each node should have a maximum of 2 parents in the WF model, but node B here has 4?):

```
ts = argutils.viz.label_nodes(argutils.sim_wright_fisher(2, 10, 100, recomb_proba=0.1, seed=320))
fig, ax = plt.subplots(1, 1, figsize=(5,10))
pos = argutils.viz.draw(ts, ax, use_ranked_times=True)
```

![image](https://user-images.githubusercontent.com/4699014/153853497-ade7c378-9aba-4d1f-a9c4-4e076bafc370.png)

**Comment by jeromekelleher** [comment]
Yes, something weird happening there all right. I'll have a look.
