### ISSUE TITLE
Greyscale ARG diagrams

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#115]
In case we want a non-colour version of fig 4 and the like, I wondered about inverting the light/dark on nodes:

![image](https://user-images.githubusercontent.com/4699014/154369515-6446fa70-23dc-4668-8f53-c568da8c286a.png)

It might reduce colour print charges and be better for photocopying? It also dinstingishes the node labels from the edge labels even more. But I'm not sure which I prefer, visually. Thoughts @a-ignatieva (who is playing with this, I think)?

Easily done by specifying the following params to `argutils.viz.draw()`

```
node_color="0.5",
font_color="white",
```

**Comment by jeromekelleher** [comment]
I'm still hoping that there's some colour intensity we can associate with nodes, summarising something about that node and its relationship the the samples.

Basically everyone has colour printers these days, and nearly all readers will be looking at it on a screen in any case. Let's not worry about colour page charges (we're not going to be publishing this in a print-first journal).

I don't think this is worth spending time on.

**Comment by hyanwong** [comment]
Fair point. I will work on the colour intensity thing, but I don't think we want to introduce it in this figure: it is more suitable to introduce the colouring / intensity in figure 5.

**Comment by jeromekelleher** [comment]
OK - can we close this issue then?

**Comment by hyanwong** [comment]
Let's see what @a-ignatieva says, and then close.

**Comment by a-ignatieva** [comment]
I like greyscale figures personally, and think this looks nice! But I also agree it's not mad important. 

I'm having a go at having pictures on the nodes now - where should I put the results if I come up with something good? In a new discussion?

**Comment by hyanwong** [comment]
> I like greyscale figures personally, and think this looks nice! But I also agree it's not mad important.

Thanks, and I agree. I'll close this now that we all know what the various options are.

> I'm having a go at having pictures on the nodes now - where should I put the results if I come up with something good? In a new discussion?

If you actually have code to generate it, why not put it as a draft PR and we can discuss it there. Otherwise a discussion is fine too, I guess.
