### ISSUE TITLE
Fig 3: point out that the edges split in the recombinant rather than the generation above

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#118]
The WF pedigree diagram is our chance to point out that the edges *need* to split one or more generations *after* the individuals in which the recombining chromosomes occur. In other words, we locate the edge split in the recombinant, not in the recombining genomes. There is no way in this diagram that we can treat I3 as a single recombination node, because it represents 2 separate recombinations.

This may also be a good time to point out that multiple independent recombinations can have the same parent ("recombining") genomes.

**Comment by jeromekelleher** [comment]
I don't follow the first point, but definitely this is the opportunity to talk about these complications.

**Comment by hyanwong** [comment]
Take the plot in fig 2. If we draw the edges diagonally (red), it becomes clearer. The node at which the edges split from each other is node 1, not node 3. If the y axis is meaningful, and this was a WF model, node 3 would be at time t+1 and node 1 at time t. Therefore in the RH diagram the edges split (backwards in time) in generation t, i.e. 1 generation below when the recombination would conventionally be thought to have occurred (generation t+1).

<img width="551" alt="Screenshot 2022-02-17 at 08 45 33" src="https://user-images.githubusercontent.com/4699014/154438617-ba5189d4-26ad-45ac-b6a4-e1e02cf8988a.png">

This is exactly the pattern seen in the lines drawn over the pedigree. The edges from individual 3 meet (forwards in time) in individuals 1 and 2, in the a generation "after" that when conventionally, the recombination is thought to happen.

**Comment by hyanwong** [comment]
This is now in Fig 3.
