### ISSUE TITLE
Add fully simplified trees to Fig 5.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#123]
When explaining it's helpful to be able to point it out. I think readers will appreciate being able to compare the raw trees from (a) with the final fully simplified product.

**Comment by hyanwong** [comment]
Yep, completely agree.

**Comment by hyanwong** [comment]
I'm thinking that it is *really* useful to have the trees from all 4 examples. So how about something like this (obviously I need to tweak the graph plots on the left a bit better, but that should be easy):
<img width="673" alt="Screenshot 2022-03-09 at 13 52 49" src="https://user-images.githubusercontent.com/4699014/157455433-a7d71a6d-921b-4140-9019-d0e0be2e106a.png">
