### ISSUE TITLE
Show recombining parents in left-to-right order?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#124]
Consider the ARG in (a), and the path for node D in the final tree. We go through D H K N R S.

![args](https://user-images.githubusercontent.com/2664569/154681283-5892bae7-7ad5-41a4-8639-0d5c19c12a2d.png)

It would be *slightly* more intuitive if N and O were swapped here, so that you can follow the right hand path up the graph.

Is this possible/worth doing @hyanwong ?

**Comment by hyanwong** [comment]
Yeah, should be easy to tweak on the ARG diagram using tweak_x. Might as well change the labels to get them in alphabetical order too.
