### ISSUE TITLE
Make node formatting consistent between later figures

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#126]
Now that we are happy with the hamburgers in fig 4, I think that we should similarly have ovals nodes in fig 3b and fig 5. In fig 5 we are intending to have different fill our outline colours depending on the node taxonomy, but I don't think this should interfere.

**Comment by jeromekelleher** [comment]
I'm not bothered either way - there's a purpose to them being ovals in fig 4, whereas there's not really in other figs.
