### ISSUE TITLE
Labelling in Fig 2

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#127]
A minor suggestion, but if by the time we get to fig 2, we haven't defined the nodes as being natural numbers, would it be sensible to label nodes 3 and 4 in the RH diagrams 3a and 3b instead? That way subfigs (a) and (b) are more comparable. However, we would need to explain in the caption that this is simply for ease of comparison, and the actual encoding uses integers, so it may not be worth it. Alternatively we could use a different labelling so that the recombination node in (a) is number 6, and then the 2 different nodes in (b) would presumably be 6 and 7. There's no reason why the oldest node should be the highest number.

Either way, we should sort out the figure formatting so that the nodes (e.g. 0, 1, and 2) are at the same vertical position on the page.

**Comment by jeromekelleher** [comment]
I like using plain integers here just to emphasise the point that this is all you need to represent them: these aren't complex linked objects in memory (which is how a lot of people think of graphs, I feel) but just plain ole integers.

Open to ideas about the specific numbering we use all right though.

**Comment by hyanwong** [comment]
Obsoleted by https://github.com/tskit-dev/what-is-an-arg-paper/pull/134
