### ISSUE TITLE
Main 2 changes to the Griffiths ARG, and explaining the 2 node convention

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#128]
In the text we say

> Fortunately, it is straightforward to generalise the classical Griffiths encoding to both simplify implementations and to encompass any possible pattern of genetic inheritance. We require only two changes. Firstly, we let nodes in the graph model genomes rather than events. As we see in the next section, this allows us to model complex patterns of inheritance without classifying different types of node. The second change we must make is to associate the details of inheritance intervals with edges rather than as breakpoints associated with recombination events and edge ordering rules.

I agree completely with this. We should possibly add a 3rd, (IMO more minor) change, which is that by convention, we also strongly suggest that recombinations are encoded using 2 genomes (nodes) rather than one (Fig 2). I would like to point out that this isn't strictly necessary, for a gARG (hence the first 2 changes are the most important), but it makes simulating the ARG much easier, and more importantly, it means that we can merge edges without changing the meaning of the graph (i.e. we can store diamonds without requiring multiple edges).

However, the caption for Fig 2 seems not quite to follow this train of thought. It says

> ... The most important change between the two encodings is to represent a recombination event (node 3 in A) by two parent genomes (nodes 3 and 4 in B) and explicitly storing the interval that the child inherits from each parent along the two corresponding edges. 

I would probably put the interval storing first, and rephrase a little.

**Comment by jeromekelleher** [comment]
Yes, good point. "A third (technically optional, but practically useful) change is to describe recombinations in terms of two parental genomes rather than a single node representing the recombined gamete (or equivalently, event)"

Or something along those lines.
