### ISSUE TITLE
Synonyms for "local" edge annotations

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#129]
We use the word "local" to mean "localised along the genome", e.g. a local (=marginal) tree. As discussed with @jeromekelleher, we could do with a different word to describe the fact that a non-sample-resolved gARG has edge annotations which are "local" in that they show the entirety of the genome inherited from the parent or passed to the child, without reference to any samples further down the tree.

It's basically the idea that in this case, a node can only "see" the inheritance process from its parents or to its children: there's no concept of having run the Hudson algorithm to reduce the edge spans in any way. We can collect possible alternative adjectives in this issue, then decide which, if any, we like.

**Comment by jeromekelleher** [comment]
How about something like "immediate inheritance"?

**Comment by hyanwong** [comment]
Yes, I like that.

**Comment by hyanwong** [comment]
Here's another suggestion "entire edge encoding" (the Griffiths scheme) vs "sample-resolved edge encoding". The implication is that the entire genomic section passed on from parent to child is encoded in the first version.
