### ISSUE TITLE
Convert function for kwarg

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#133]
Following the pattern set for argweaver in #130, we'd like a ``convert_kwarg`` function.

This needs:
- A function ``convert_kwarg(infile)`` in argutils/convert.py. 
- Some example files in the ``examples/`` directory that we can test on.
- A test class TestConvertKwarg in argutils/tests with some very basic tests, just to make sure it's roughly working.

@a-ignatieva - you're the obvious candidate here, fancy picking this up?

**Comment by jeromekelleher** [comment]
Feel free to ping me if you have any qusetions!

**Comment by a-ignatieva** [comment]
I've made a draft PR with what I've got - just need to test that it works properly! Will do that by the end of this week definitely. Sorry for the delay! I've been distracted by world events.

**Comment by jeromekelleher** [comment]
Thanks @a-ignatieva, no worries at all. Hope you're OK.
