### ISSUE TITLE
Brief comment on single vs multiple chromosomes

### ISSUE THREAD

**Issue by JereKoskela** [tskit-dev/what-is-an-arg-paper#136]
As discussed in #135, it would be good to find a place for a brief explanation of the fact that it is sometimes necessary to define explicitly multi-chromosome ARGs, but that we're only talking about the single-chromosome case for (relative) simplicity. The more obviously reasons for multi-chromosome models include fitness functions with interaction between chromosomes, or multiple merger models which can feature simultaneous mergers in all chromosomes.

I'll put a draft together.

**Comment by hyanwong** [comment]
By "multi-chromosome ARGs" do you mean ones that keep the ancestral correlation between adjacent chromosomes? Like the discussion of the WF model [here](https://github.com/tskit-dev/msprime/issues/848)

**Comment by JereKoskela** [comment]
> By "multi-chromosome ARGs" do you mean ones that keep the ancestral correlation between adjacent chromosomes? Like the discussion of the WF model [here](https://github.com/tskit-dev/msprime/issues/848)

Yes. Both the reasons I listed above imply that the correlation does not diminish as you look further back in time, which is why it's essential to keep it in the model.

**Comment by hyanwong** [comment]
Yes, that makes sense. But I can't see how it would be possible to keep this in a (basic) node-annotated ARG. Perhaps I'm missing something?

**Comment by JereKoskela** [comment]
I'm not sure whether a finite-population, discrete-time WF model would throw some curve balls. I expect it probably would. But under a Hudson model, you instantaneously split up your individuals into single-chromosome lineages at time 0+, label each lineage with the chromosome for which it is ancestral, and block mergers between different chromosomes as if the population were structured. They would only split apart instantaneously anyway, so there is no point simulating the merger.

Concretely, if you have `n` lineages which are ancestral at chr1 and `m` at chr2, the total merger rate is `(n choose 2) + (m choose 2)`, rather than `((n + m) choose 2)`, and you have to be a bit careful about how to choose the two lineages to merge in an event.

Selection and multiple mergers complicate the picture by introducing more events whose rates don't split up nicely into a sum of single-chromosome contributions.

**Comment by JereKoskela** [comment]
From the point of view of storing a realisation as a node-encoded ARG, I guess there would be two options: either you augment the encoding with the ancestral chromosome, or you have to keep the much larger `((n + m) choose 2)` merger rate and will end up with a lot of instances in which two nodes merge, only to instantaneously break apart again with a breakpoint at the boundary of the chromosomes.

**Comment by jeromekelleher** [comment]
Sounds good.
