### ISSUE TITLE
Improve tree viz in example gARG fig

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#142]
It would be relatively simple to plot the node numbers inside the nodes in fig 2(c) to match the way they are shown in (a) and (b) in the same figure. See e.g. https://tskit.dev/tutorials/viz.html#a-fancy-formatted-plot for code to do it. The only problem is that we would then need to used chromium to do the conversion, as this relies on SVG2 css transformations, not yet supported in Inkscape.

**Comment by jeromekelleher** [comment]
We can do that towards the end if you like. There is some additional faffing needed with bounding boxes for using chromium though.

**Comment by hyanwong** [comment]
Yeah, no super hurry on this. We'll leave this open as a final nitpick todo.

**Comment by jeromekelleher** [comment]
Is this still relevant?

**Comment by hyanwong** [comment]
Yes, I think so. Might as well leave open.

**Comment by jeromekelleher** [comment]
It this still a live issue?

**Comment by hyanwong** [comment]
I decided that it is OK to distinguish local trees (labels outside the nodes) from graphs (labels inside the nodes). If anyone disagrees, they can reopen this.
