### ISSUE TITLE
Outline list of ARG inference methods

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#15]
#12 added an initial list of the ARG inference methods that we want to review, but is incomplete. We should complete this list, with up-to-date citations for any methods that we know about, and a brief description for each method. One this list is complete, we can then start to classify and to create a narrative. We should aim for completeness, and try to list every published ARG inference method.

(This issue can be closed when we're happy that we have all the relevant citations).

See #14 for discuss of the purpose of the section.

**Comment by jeromekelleher** [comment]
It might be worth considering having a table with some columns for classifications too. We might just list more recent methods, as a full listing would probably be a lot of work (trying to figure out exactly what people inferred in 20 year old methods is probably not practical, or a good use of time).

**Comment by jeromekelleher** [comment]
Another note: the KwARG paper has a good list of references particularly for parsimony approaches.  It's a good place to start for filling in the gaps we have.

**Comment by hyanwong** [comment]
It might be helpful to list the names of the methods, rather than simply the citation? Should I add these?

**Comment by jeromekelleher** [comment]
> It might be helpful to list the names of the methods, rather than simply the citation? Should I add these?

I'm not sure what good it would do for most of them? The majority will be unusable now, for various reasons.

I was hoping someone else might jump in here and do a bit of legwork on getting the references together etc, since you're already doing a lot Yan.

**Comment by JereKoskela** [comment]
I was already planning on entering the ones I brought up in #14 into the bibliography. I'm happy to look through the KwARG paper and add any others from there at the same time. I'm not sure how competently I can describe all of them, but it'll be a start at least.

**Comment by a-ignatieva** [comment]
I'm happy to help with descriptions of the parsimony based ones particularly. Also Recombinatorics is a good source (for the older methods).

To possibly add to the list: ARGneedle ([preprint](https://www.biorxiv.org/content/10.1101/2021.11.03.466843v1.full))

**Comment by JereKoskela** [comment]
I got as far as adding a bunch of entries to my local bibliography file. I was intending to write a bit of connective tissue to introduce them later today, or more likely tomorrow.

@a-ignatieva, would it make sense for me to do that, PR what I have, and ping you to take over from there?

**Comment by a-ignatieva** [comment]
@JereKoskela sounds good!

**Comment by jeromekelleher** [comment]
I think this is covered, closing.
