### ISSUE TITLE
Line widths off in Fig 5d

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#156]
Looks to me like the line widths are different in 5d from the others:

![line-widths](https://user-images.githubusercontent.com/2664569/157722793-b4038fdc-ad28-4142-8410-0a6655b56d57.png)

I don't see why this would be? E.g. the line from c->f should be same shoudn't it?

**Comment by hyanwong** [comment]
Didn't we go though this before? I think the only problematic one here is C->F which looks thinner in (d) because it is overlaying C->G. I guess I could try to reposition G or F somehow to make this clearer?

**Comment by hyanwong** [comment]
This is clearer, right? But messier. <img width="339" alt="Screenshot 2022-03-10 at 19 03 40" src="https://user-images.githubusercontent.com/4699014/157736160-fa80fbe5-16c1-4de9-9b4e-41e04ba29666.png">

**Comment by hyanwong** [comment]
I've jiggled it around a bit. How is this:
<img width="245" alt="Screenshot 2022-03-10 at 19 18 55" src="https://user-images.githubusercontent.com/4699014/157738442-9c7a855d-4484-4a4a-8b0b-cf9188adfe3d.png">

The X tweaks in this case are:
```
    t_x = {
        4: 15,
        12: -5,
        9: 3,
        6: -15,
        18: 15,
        17: 5,
        13: 30,
        14: -20,
        10: -10,
        15: 3,
        16: -13,
        7: -5,
        11: 5,
        8: 10,
    }
```

**Comment by jeromekelleher** [comment]
Ah yes, very good. I think we do want to see C->G all right.
