### ISSUE TITLE
Add ARGweaver output to fig 6

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#160]
I'm working on this

**Comment by hyanwong** [comment]
We need to specify a mutation rate and a recombination rate for ARGweaver. I guess I could take these from the D melanogaster model in stdpopsim?

**Comment by jeromekelleher** [comment]
Sounds like a good place to start. Probably wants Ne too I guess?

**Comment by hyanwong** [comment]
Where should we put the scripts to run these programs. For tsinfer I just embedded it in illustrations.py, but ARGweaver will be much slower, so should probably be run in a separate location and one of the output files chosen and committed to the repo.

**Comment by jeromekelleher** [comment]
In the examples directory I suppose? Should probably just commit in the tsinfer output too.

**Comment by hyanwong** [comment]
<img width="752" alt="Screenshot 2022-03-11 at 21 53 35" src="https://user-images.githubusercontent.com/4699014/157975652-905535e1-59b5-4669-828d-924363bacd19.png">
