### ISSUE TITLE
Add Relate output to fig 6

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#161]

**Comment by hyanwong** [comment]
Since we are not plotting times in Relate, I think we could convert its ".anc" format to a "proper" ARG, rather than a set or marginal trees. That's probably a fairer way to represent a Relate ARG, if we are only interested in topology.

**Comment by jeromekelleher** [comment]
Agreed. I'm interested to see what it comes up with actually, and am surprised they didn't allow for the tskit conversion on this form (I guess they didn't know how to assign node times?).

Does anyone have a good understanding of this ".anc" format? Maybe @a-ignatieva ?

**Comment by hyanwong** [comment]
I started on this yesterday, but not got anything working yet, though I have a very simple `.anc` file parser. The main issue is that Relate uses the same node numbers in each tree, without implying that the nodes are shared between trees. I think you therefore need to use the edge properties to link nodes in different trees together. I can think of 2 approaches:

1. Make each tree independent (with new node numbers for each internal tree node), then look for shared edges and merge the nodes where appropriate
2. Assume the nodes numbers are the same between trees, but as soon as a new edge (determined by different parent/.child or left/right span) is encountered, make a new node and create a mapping of relate node numbers in this tree to tskit ARG-wide node IDs.

I tried to do 2. but

**Comment by jeromekelleher** [comment]
If there isn't an obvious way to turn Relate's .anc output into an ARG then I think the first thing to do is just use their tskit output.

After that, if we don't have someone on the team who has expertise with the format, then we should probably consider looping in someone who does. There's no point in us spending time trying to reverse engineer the format if it doesn't have an obvious and documented connection with an ARG encoding that we discuss. (This is why we dropped SARGE #33)

So, I suggest we just use the direct Relate output for now and revisit in later stages.

**Comment by a-ignatieva** [comment]
Think this might help with approach 1: there's a modified version of the Relate -> tskit conversion [here](https://github.com/leospeidel/relate_lib/tree/devel) which stores information on equivalent nodes in the metadata. So the metadata for each node in a tree is a pair of integers that gives the equivalent node IDs in the trees to the left and right (if the branch above the node is still there). Leo did this because we needed a way of accessing equivalent branches - but I think there was some difficulty in merging nodes and adding edge spans in directly.

**Comment by hyanwong** [comment]
Ah, that might be really helpful, thanks @a-ignatieva

**Comment by hyanwong** [comment]
I wonder what the difficulty in merging nodes was? Did you want to keep the times, perhaps?

**Comment by hyanwong** [comment]
Here's some code which works on the Kreitman dataset. Does it make sense @a-ignatieva ? It doesn't work on the example dataset in `relate_lib` because it claims that once the nodes are merged, the graph is no longer acyclic (try it!). I can well believe that the process or merging adjacent edges in a JBOT can create cyclical graphs, but it's possibly that my code is wrong:

```
import tskit
import numpy as np
import networkx as nx
import collections

def ts_JBOT_to_ts(ts):
    """
    Convert a tree sequence from Relate (converted via relate_lib/bin/Convert, which provides adjacent nodes via metadata
    into a tree seque3nce in which the nodes have been merged, but new times allocated
    """
    # make a map of relate node_id -> canonical node id (the first one used in relate)
    node_map = {}
    G = nx.DiGraph()
    for node in ts.nodes():
        md = np.fromstring(node.metadata, dtype=int, sep=' ')
        if len(md) == 0 or md[0] == -1:
            node_map[node.id] = node.id
            G.add_node(node.id, flags=node.flags, time=node.time, relate_times={node.id: node.time})
        else:
            left_node = md[0]
            node_map[node.id] =  node_map[left_node]
            assert G.nodes[node_map[left_node]]["flags"] == node.flags
            G.nodes[node_map[left_node]]["relate_times"][node.id] = node.time

    # collect all the intervals for each edge (will be squashed later)
    edges = collections.defaultdict(list)
    for e in ts.edges():
        edges[(node_map[e.child], node_map[e.parent])].append((e.left, e.right))

    # Turn this into a graph so we can do a topological sort
    for k, v in edges.items():
        G.add_edge(*k, intervals=v)
    # Set arbitrary times by topological_sort
    for i, n in enumerate(nx.lexicographical_topological_sort(G)):
        if G.nodes[n]["flags"] & tskit.NODE_IS_SAMPLE:
            assert G.nodes[n]["time"] == 0
            G.nodes[n]["time"] = 0
        else:
            G.nodes[n]["time"] = i

    # Create a new tree sequence using these times
    tables = tskit.TableCollection(ts.sequence_length)
    tables.nodes.metadata_schema = tskit.MetadataSchema.permissive_json()
    for n in range(max(G.nodes())+1):
        try:
            node = G.nodes[n]
            tables.nodes.add_row(flags=node["flags"], time=node["time"], metadata={"Relate_times": node["relate_times"]})
        except:
            tables.nodes.add_row(time=0) # dummy, unused

    for child, parent, attribute in G.edges(data=True):
        for i in attribute["intervals"]:
            tables.edges.add_row(child = child, parent=parent, left=i[0], right=i[1])
    tables.sort()
    tables.simplify()
    tables.edges.squash()  # probably don't need this: I think simplify() squashes edges
    return tables.tree_sequence()
```

Here's the output for the Kreitman one. though:

```
import sys
import matplotlib.pyplot as plt
import argutils

ts_orig = tskit.load("/Users/yan/Documents/GitHub/what-is-an-arg-paper/examples/Relate_output/Kreitman_SNP.trees")
ts_merged = ts_JBOT_to_ts(ts_orig)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 12), sharey=True)
argutils.viz.draw(ts_orig, ax1, draw_edge_widths=True, node_arity_colors=True)
ax1.set_title("JBOT")
argutils.viz.draw(ts_merged, ax2, draw_edge_widths=True, node_arity_colors=True)
ax2.set_title("merged_edges")
```
<img width="828" alt="Screenshot 2022-03-27 at 22 05 33" src="https://user-images.githubusercontent.com/4699014/160300987-a1270cc3-d3a1-426b-9b2e-f7b985e160ee.png">

**Comment by hyanwong** [comment]
> There's no point in us spending time trying to reverse engineer the format if it doesn't have an obvious and documented connection with an ARG encoding that we discuss.

I think in the Kreitman example, the number of shared nodes / edges in the Relate inference is enough that we can check the example above by hand, so that we don't need to worry about the reverse engineering problem in general.

I would be interested to know if the comments above about Relate producing cyclical graphs are correct, though.
