### ISSUE TITLE
Trivial viz nitpick: truncated ovals

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#165]
In Fig 4 the ovals have their RH edge truncated slightly. I wonder if @a-ignatieva knows why? Completely trivial, obviously, so no hurry to solve this!
<img width="542" alt="Screenshot 2022-03-11 at 14 40 14" src="https://user-images.githubusercontent.com/4699014/157888757-7b1e6757-d1ba-47d8-a2b3-e103c465db61.png">

**Comment by a-ignatieva** [comment]
Ew! I'll have a look.
