### ISSUE TITLE
Rotate branches in fig 5 tree sequences

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#166]
The local trees in fig 5 start with their tips in the order B A C D, rather than A, B, C, D as in the graph viz. It should be easy to plot the trees with the branches rotated. I tried to change this [here](https://github.com/tskit-dev/what-is-an-arg-paper/blob/4c6f264e07cad6b7607b2e7888de0ab23a07045c/illustrations.py#L241), by changing the node order, but couldn't get it to work.

**Comment by jeromekelleher** [comment]
You'd probably need to think about the order the edges are listed in, and then tell draw_svg() to use the tree order rather than the default minlex
