### ISSUE TITLE
Recombination nodes are optional figure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#17]
We have  placeholder figure (``fig-recombination-nodes``) whose caption current reads:

> Recombination nodes are optional in an edge-annotated ARG. (A) A simulated ARG including all recombination nodes. (B) The same ARG with recombination nodes removed. (C) The corresponding sequence of trees.

I'm imaging that do a small simulation with msprime's ``record_full_arg`` (with the single recombination node encoding) and we draw the graph in (A). We then simplify this tree sequence to remove the recombination nodes, keeping the node IDs constant for clarity, and draw this in (B). We then use ``draw_svg`` to draw the tree sequence in the standard form and show this in (C).

Since this is (probably?) two long things and one wide thing it may be best to do this as a two-row display like this?
```
 ---------
| A | B |
|   C    |
---------
```

@hyanwong, this seems right up your street - can I assign it to you?

**Comment by hyanwong** [comment]
Please do assign it to me

**Comment by hyanwong** [comment]
By the way, are you happy with the colour scheme used for nodes in e.g. https://user-images.githubusercontent.com/4699014/146042766-5a606482-4e72-44f5-b1af-eee793ea51cf.png. I think it is useful to use colour like this.

**Comment by jeromekelleher** [comment]
Looks great! It's easy enough to tweak later on anyway if we want, right?

**Comment by hyanwong** [comment]
Here's a rough example. I'll look for nicer random seeds
![Screenshot 2022-01-10 at 14 58 55](https://user-images.githubusercontent.com/4699014/148787129-789b14d7-7acc-4c3d-a232-9210d025a6a2.png)

**Comment by jeromekelleher** [comment]
Yes, that's awesome! :star_struck:

**Comment by jeromekelleher** [comment]
(looks like the bottom figure isn't using the same node IDs though?)

**Comment by hyanwong** [comment]
> (looks like the bottom figure isn't using the same node IDs though?)

Oh yes, I need to relabel them. Or plot out the unsimplified ts. Here's another with a whole load of recombinational topology simplified away:
![Screenshot 2022-01-10 at 15 09 29](https://user-images.githubusercontent.com/4699014/148788883-d7a758a6-db09-4d39-bd30-406390dd3724.png)

**Comment by hyanwong** [comment]
I forgot we can show curvy arrows. Here's the same as the one just above, but with multiple edges more clearly shown, and the correct node numbering on the trees.

Two annoyances: 
1. It would be nice to force the trees in the bottom plot to have the same ordering of node numbers. I guess I might be able to do this by relabelling the sample nodes
2. it's perhaps a bit annoying that the 3 first trees only differ in the age of the root, and not in topology.

![Screenshot 2022-01-10 at 15 32 24](https://user-images.githubusercontent.com/4699014/148792628-4fcab7f0-468b-434a-81ab-f7efac3a8e40.png)
a

**Comment by hyanwong** [comment]
I've had a good hunt through random seeds, and this is still the best example. Here's what I have with a bit of tweaking. I'll upload the code now.


![Screenshot 2022-01-10 at 17 00 47](https://user-images.githubusercontent.com/4699014/148806736-621dc562-81d9-44e3-8778-c9a3bd06fc90.png)

**Comment by jeromekelleher** [comment]
This is beautiful Yan!

**Comment by hyanwong** [comment]
There is an interesting occurrence in this particular example which may bear more investigation. I have commented on in in some commented out sections in the latex doc. The simplification process has actually created 2 edges above node 4, where 1 would suffice. That's because the lineage goes entirely through node 11, but in some trees, node 11 is a unary node. This is an example of a case where removing unary nodes both increases the number of edges and also generates a potentially misleading topology. It would be nice if there was a way to identify cases like this during simplification, but I think that would require very deep thought. It might, however, be worth a discussion on the tskit discussion boards.

**Comment by petrelharp** [comment]
This gives perhaps some good open questions? "Given a tree sequence, what is a good lower bound on the minimum number of edges required to represent it by a consistent tree sequence?" and "What is an algorithm that finds a consistent tree sequence with the minimum number of edges?" (where "consistent" means here having node identities agree)

**Comment by hyanwong** [comment]
Can we say that if simplification ever creates a node with more edges above it than were in the original tree sequence, we have gone wrong somehow? Or can we imagine cases where this would lead to a reduction in overall edge number? (NB should we move this to a tskit discussion)

**Comment by jeromekelleher** [comment]
I agree this is interesting, but I think it's beyond the scope of this paper. We'll be doing well if we get people to understand the basic simplify-to-coalescence nodes process. It is something we could mention in the discussion or elsewhere, that there are interesting questions about what the "optimal" (smallest number of nodes and edges) representation of an input ARG is. I guess the current version is "node optimal".

Would you mind opening a discussion on tskit summarising this when you get a chance please Yan?

**Comment by hyanwong** [comment]
Opened at https://github.com/tskit-dev/tskit/discussions/2089. But note my point there, which I think is relevant to this paper:

> We therefore need to be careful to say that in an ARG diagram like the above, even if it appears that there are separate routes through the topology, they may (weirdly?) actually correspond to the same lineage.

**Comment by jeromekelleher** [comment]
This is something we should probably discuss all right, as we'll want to mention that tsinfer keeps unary nodes for this reason.

I don't think there's anything weird about it, we're already dropping any number of nodes for genomes along the pedigree where nothing interesting happens. We're just saying in this simplification that we're only interested in coalescences, and there is a necessary loss of information there.

This is the kind of nuance that is currently missing from the ARG discussions I think, so good to bring it in. Maybe we should open an issue to track (and close this, as the figure is in?)
