### ISSUE TITLE
Wiuf & Hein ARG (Fig 4) is wrong in the original paper

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#172]
The original has a loop at the top in bold, which is part of the big ARG but is avoided by the Hudson algorithm. The paper shows it like this:

![image](https://user-images.githubusercontent.com/4699014/158603128-d4fab7cc-883d-4400-a896-a98238885527.png)

I think we are missing that upper loop in Fig 4 currently.

![image](https://user-images.githubusercontent.com/4699014/158603595-c609845f-13b6-435a-a167-ffc845d40279.png)

 It might be nice to show that it disappears in the RHS (as does the edge F,J,N, which is the other part of the big ARG.

**Comment by hyanwong** [comment]
Oh, no I'm wrong here. It does look like it is in. So why do we still have those edges?

**Comment by a-ignatieva** [comment]
Hm yeah confusing. I think the Wiuf and Hein figure is correct though? It's a recombination in a part of the genome that's already reached MRCA - so the {} correctly show the lineages no longer carry any ancestral material.

**Comment by a-ignatieva** [comment]
Maybe U and V hamburgers should be black in the [0,1] region, and edges ST and TW should be deleted? Though the graph is just the output of simplify_keeping_all_nodes(), so should that have removed these edges?

**Comment by hyanwong** [comment]
The branch from O->S  in our plot is marked as `[0, 7]`. In theirs it is `[2, 7[`. I think that's the problem?

**Comment by a-ignatieva** [comment]
I think that's because at O [0,2] reaches MRCA right? so [2,7] denotes the remaining non-coalesced ancestral material carried by that edge.

**Comment by hyanwong** [comment]
Oh you are right, just discussing with Jerome

**Comment by hyanwong** [comment]
Yep, the top loop is present in our version be cause we aren't running the full Hudson algorithm (we aren't stopping when all material at a position is coalesced.
