### ISSUE TITLE
Node type classification 

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#177]
I've been thinking about how we classify nodes in an ARG, which is of relevance to @awohns who I think has volunteered to colour them in on the diagrams. I think that the clearest classification from a Graph POV is to shade the symbol by the relative span for which it is a coalescent node (with an empty symbol if it is never a coalescent node), and to use something else (e.g. node symbol) to indicate if it has (0 or 1) parents versus greater than 1 parent (i.e. it represents a recombinant, either directly or indirectly). For example, we could mark nonsample nodes with greater than 1 parent with a diamond symbol, leaving the square symbol for sample nodes, as we currently do.

This feeds into figure 5, in particular which nodes vanish during various sorts of simplification.

## topologically redundant nodes

The nodes that we can seemingly remove with little effect on graph topology - i.e. they are 'topologically redundant - are "pass though" nodes (nonsample nodes in the graph with 1 parent and <2 children). We can apply this iteratively which removes diamonds and possibly some other more complex internal structures from the graph. That's what we do to move from fig 5a to fig 5b. This is equivalent to removing all empty circular nodes

## recombinant-only nodes

The second class of nodes we could remove are those like node `I` which are nonsample nodes with <2 children in the graph but >1 parent. These are "recombinant" nodes, capturing one or more historical recombination events. They are guaranteed to be always unary in all the trees (because a node can only have one parent at each genomic position). These will appear as empty diamonds in the suggested scheme. They are removed when going from Fig 5b to Fig 5c.

## partially coalescent nodes

The third class of node we can treat are those which are partially coalescent (i.e. which are not fully shaded). These nodes are not removed from the graph by simplification, but edges that connect them are shortened, so that they are never unary nodes in any tree. This process leads to all nodes becoming fully shaded circles (if only coalescent) or diamonds (if >1 parent)

# Problems

One fly in the ointment: if we use the 2 parents to define a recombination, then they often will be "pass through" nodes, and hence topologically redundant (e.g. nodes K and L in figure 5a). I guess that's OK, is it? We still retain the recombinant node (e.g. I) because it has 2 parents, so we still have some idea that a recombination has occurred: it's just that we don't know exactly when.* An alternative node classification would be to look to see if if a node has >1 parent, and if so, consider the *2 parents* as a special class of node. But we still wouldn't know that these marked the time of the recombination, because it's only a simple full gARG convention that the 2 parents are the nodes which came together to create the recombinant.

**Comment by hyanwong** [comment]
I guess if we do adopt the 2 RE node convention, we could have some sort of separate layer on top of this scheme to mark these "parent" nodes. It would have to be combined with the existing scheme, though, as RE nodes can also be coalescent nodes (and therefore shaded) or can themselves be recombinants (and therefore a different symbol). Perhaps they could have names marked with an asterisk, or something? Seems a bit messy, but then I think this is not an inherent property of the graph, but a feature of our specific interpretation of the graph in this context.

**Comment by hyanwong** [comment]
An alternative to having 2 symbols for 1 vs > 1 parent of a node is to have the brightness being the number of children (white = 1 child) and some isoluminant colourmap used for e.g. the number of parents. That might be a nice way to show differences in Fig 6, but we would have to pick the colourmap values carefully.

**Comment by jeromekelleher** [comment]
Sounds good, thanks @hyanwong. I prefer the latter idea of having numerical values associated with nodes to identify their "recombinantness" - one of the things we're trying to emphasise is that nodes are nodes, and having two qualitatively different ways of drawing them confuses this message. 

I don't think we need to worry about visually identifying the topologically redundant nodes. This is easily defined in a graph theoretical way, as we do in the text. A "super diamond" is a graph component that's connected to the rest of the graph by exactly one node in the leafward and rootward directions. There's no need to talk about iterative algorithms to remove them or anything, we can just state that.

**Comment by JereKoskela** [comment]
At the risk of sounding like I'm jumping on a bandwagon, I was just typing out something very similar to Jerome's comment above.

**Comment by hyanwong** [comment]
> one of the things we're trying to emphasise is that nodes are nodes, and having two qualitatively different ways of drawing them confuses this message.

Yes, I hadn't thought of that. This is a very good point.

> I don't think we need to worry about visually identifying the topologically redundant nodes. This is easily defined in a graph theoretical way, as we do in the text. A "super diamond" is a graph component that's connected to the rest of the graph by exactly one node in the leafward and rootward directions. There's no need to talk about iterative algorithms to remove them or anything, we can just state that.

Again, I agree with this. I like "super diamond".

I'll see what it looks like with the simple colouring.

**Comment by hyanwong** [comment]
This is interesting. Here's a first attempt at colouring: red is a root (no parents), yellow is one parent, green->blue gives successively more parents of a node. Node lightness gives the span for which the node is coalescent (that doesn't work so well for ARGweaver, though, because it has lots of recombination nodes which are not recombinants). Interesting that in this case, the root node in ARGweaver is only present as a coalescent node on a tiny fraction of the genome (I looked: it's only in the last of 18 trees).
<img width="1231" alt="Screenshot 2022-03-21 at 12 36 39" src="https://user-images.githubusercontent.com/4699014/159262238-a3ea5579-0395-45aa-874a-e54bf6e251ac.png">

**Comment by jeromekelleher** [comment]
> Interesting that in this case, the root node in ARGweaver is only present as a coalescent node on a tiny fraction of the genome (I looked: it's only in the last of 18 trees).

That is interesting, and from first glance appears to contradict the information from the inbound edge thicknesses. Ah, but the right-hand edge to the root is all coalesced except for the little thread coming in from the left. Tricky.

**Comment by hyanwong** [comment]
Here it is with a ring of colour around each symbol, which means you can see the colour of the ones that have no or little coalescence:

<img width="1247" alt="Screenshot 2022-03-21 at 12 51 36" src="https://user-images.githubusercontent.com/4699014/159264484-9012990b-7f5f-4be2-91da-861bafeb420e.png">
.

**Comment by hyanwong** [comment]
Also this: 

<img width="734" alt="Screenshot 2022-03-21 at 13 04 55" src="https://user-images.githubusercontent.com/4699014/159266735-a6cfd157-dba1-4845-b427-d3227655995a.png">

**Comment by awohns** [comment]
This looks great @hyanwong!
I think having all the colors may be a bit redundant though. For instance, you could just look at the graph to distinguish root nodes and nodes with multiple parents. On the other hand, knowing the relative span where a node is a coalescent node is not as readily understandable from the drawing: hence the surprising result with the ARGweaver root node.
Also, it's surprising to me that the "JBOT" has only three trees(?!) That sort of makes me curious where the mutations are, might be worth a very light strike through branches with a mutation?

**Comment by hyanwong** [comment]
Yes, the colours are indeed redundant if you look carefully. But I think they are helpful in Figure 6, as they highlight fairly stark differences between inferred trees which are otherwise rather hard to discern amid all the lines.

**Comment by jeromekelleher** [comment]
The colour is definitely useful - you could have, e.g., two half-thickness lines coming into a node and yet have no coalescence at all. That would be very hard to see just from the thickness of the outgoing line(s).

**Comment by jeromekelleher** [comment]
It is surprising that there is such a wide range in the numbers of trees inferred by the methods. That breakpoint "line" along the bottom that we talked about would be really interested here @awohns

**Comment by awohns** [comment]
I see your points, but just to clarify I was referring to the colors for "root" and "multiple parents", not the node lightness Yan used for coalesence, which I agree is helpful.

**Comment by jeromekelleher** [comment]
Ah, my bad re colours

**Comment by jeromekelleher** [comment]
Yes, that could just be confusing, I agree.

**Comment by hyanwong** [comment]
Personally I find it quite useful to be able to see at a glance how many of the nodes have only a single parent (or no parents) compared to those that have 2 or more. But happy to go with the consensus here, or come up with a different scheme (suggestions also welcome)

**Comment by hyanwong** [comment]
Merged in https://github.com/tskit-dev/what-is-an-arg-paper/pull/175

**Comment by hyanwong** [comment]
Closing this and opening another issue to track the explanation.
