### ISSUE TITLE
Should KwARG output have one node per recombination?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#178]
It looks to me like the KwARG plots have two parent nodes per recombination, but it would probably be more correct if it had one (since that's what it natively produces). I think it would be misleading if we represented the ARGWeaver output has having one node per recomb vs the two nodes for KwARG (see examples in #177). It should be a straightforward change to make.

Have I got this right @a-ignatieva? Do you think it's better as it is, or do you agree with the proposal?

**Comment by a-ignatieva** [comment]
Two nodes seemed like the natural thing to do based on the text output (like the file in the examples folder) - at each recombination event it adds a new sequence (node). Though the .dot etc graphs it outputs do have one node per recombination. I would stick with two I think?

**Comment by jeromekelleher** [comment]
If you think that's the most natural representation of KwARG's output @a-ignatieva then sure, let's keep it.
