### ISSUE TITLE
Fig 6: Visual comparison of ARGs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#18]
It would be great if we could have a figure showing the ARGs inferred by different programs for some small dataset. I don't know whether this will be practical or if the visual depictions will convey any real information, but it would be nice if they did. From a high-level, we'd expect (say) Relate, tsinfer and ARGWeaver ARGs to look different in the following ways:

1. Internal nodes in Relate ARGs should be disjoint across marginal trees, so there'll be more internal nodes. I'm imaging we might see some graph structure where we see several disconnected components (except for sample edges). There will be no recombination nodes.
2. Tsinfer ARGs should have fewer disconnected components, and also not have recombination nodes.
3. ARGweaver ARGs should have recombination nodes.

Again, it's hard to say whether this will be practical, but I think it's definitely worth having a try. 

Wrt to dataset, it would be ideal if we could compare using the Kreitman dataset (Kreitman M. (1983) Nucleotide polymorphism at the alcohol dehydrogenase locus of Drosophila melanogaster. Nature, 304, 412–417.) as this is the classical dataset for benchmarking ARGs (used recently in the KwARG paper). The dataset is very small (I *think* this is all of it):

![Screenshot from 2022-01-10 13-00-18](https://user-images.githubusercontent.com/2664569/148770103-b5226482-76d1-44bb-a004-40395fa700de.png)

Again, not sure how practical this would be, but I think it's worth a go as it strikes the right note of continuity with older methods.

@hyanwong any thoughts?

**Comment by hyanwong** [comment]
We can definitely try this. I'll post what it looks like here.

**Comment by jeromekelleher** [comment]
Great, thanks @hyanwong. Assigning you for the moment so.

**Comment by hyanwong** [comment]
Data is at https://github.com/a-ignatieva/kwarg/blob/main/source/kreitman_snp.txt

**Comment by hyanwong** [comment]
FWIW, here is the current ref sequence in NCBI:

http://metazoa.ensembl.org/Drosophila_melanogaster/Location/View?db=core;g=FBgn0000055;r=2L:14615488-14618223

**Comment by hyanwong** [comment]
Sub-issues are #160, #161 and #162.

In general, I think we should rotate the sample labels and write the Kreitman sample names (Wa-S, Fl-1S, etc, currently stored in the individuals metadata) underneath the sample nodes, and rotated 90 degrees so that they fit. This would also allow us to make the sample node symbols smaller and so avoid clashing.

However, text rotation requires switching to chromium rather than Inkscape for the SVG rendering (see https://github.com/tskit-dev/what-is-an-arg-paper/issues/142)

**Comment by jeromekelleher** [comment]
All sounds good. 

An option to avoid vertical labels would be to use A, B etc and explain what they are in the caption. Wouldn't need too much space, right?

**Comment by hyanwong** [comment]
I forgot that this is nx.draw, so I sorted the vertical labels without having to resort to chromium in this case :tada:

**Comment by hyanwong** [comment]
<img width="999" alt="Screenshot 2022-03-13 at 17 49 19" src="https://user-images.githubusercontent.com/4699014/158072436-dab789cb-6547-45e1-995e-b3381a5963d7.png">

**Comment by jeromekelleher** [comment]
Fantastic. This is looking really great!

Love the way, e.g., all three methods group Fr-F, Wa-F and Af-F together in the same way, but tsinfer makes a polytomy.

**Comment by hyanwong** [comment]
The ARGweavert output (as you might expect) can look radically different depending on the random seed used. Not sure we can do much about this, though.

**Comment by JereKoskela** [comment]
> The ARGweavert output (as you might expect) can look radically different depending on the random seed used. Not sure we can do much about this, though.

It's something of a tangent to the main point of the paper, but I think it would be useful to mention this in the text in a brief comment. It is a nice illustration of the fact that many different ARGs explain a given data set, and that relying on a single one can bias downstream analyses.

**Comment by hyanwong** [comment]
FWIW, here is what the plots look like when the tree sequences for ARGweaver, KwARG, and tsinfer have been fully simplified:
<img width="795" alt="Screenshot 2022-03-27 at 18 22 54" src="https://user-images.githubusercontent.com/4699014/160293029-385f3c8b-214e-4abe-85ae-53dd46b5cb19.png">
