### ISSUE TITLE
Describe and improve node colouring scheme (figs 4 and 6)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#180]
In #177 I suggested a colouring scheme where brightness indicated proportion of coalescence of a node, and colour (hue) represented the number of parents of a particular node. Although this colouring helps to highlight recombinant nodes, @awohns pointed out that the colours (but not the brightness) are somewhat redundant, as you can see the number of parents by careful inspection of the node. Nevertheless, we might be able to improve the colouring scheme.

At the moment, we have

<img width="26" alt="Screenshot 2022-03-21 at 17 06 07" src="https://user-images.githubusercontent.com/4699014/159326191-1639314c-655f-4f6e-9b96-49ec54fe01d4.png">: no parents (i.e. a root, although it may be possible for a node to be a root in one tree and not in another: we have no colouring 
scheme suggestions that show this)

<img width="22" alt="Screenshot 2022-03-21 at 17 06 26" src="https://user-images.githubusercontent.com/4699014/159326258-a2124553-27d5-4429-a917-9f53563f5148.png">: one parent

<img width="20" alt="Screenshot 2022-03-21 at 17 07 00" src="https://user-images.githubusercontent.com/4699014/159326394-5a985864-494b-4bf0-b17c-7b6ba54631ba.png">: 2 parents

<img width="20" alt="Screenshot 2022-03-21 at 17 15 07" src="https://user-images.githubusercontent.com/4699014/159327766-cfa8eaf6-8963-4a02-bc09-88e3fae4cbac.png">: 4 parents - with increasing blue as more parents are added to a node

We need to make a key, describe this scheme in the figure text, and possibly improve upon it.

Here's an example:

<img width="1077" alt="Screenshot 2022-03-21 at 17 16 57" src="https://user-images.githubusercontent.com/4699014/159328115-399599f7-71df-4ee4-8649-1e192f2680c1.png">

**Comment by jeromekelleher** [comment]
Can you paste in the updated figs here with the edges row please @hyanwong? We need to take this into account also.

**Comment by hyanwong** [comment]
Here's how it currently looks.

<img width="788" alt="Screenshot 2022-04-05 at 10 34 29" src="https://user-images.githubusercontent.com/4699014/161724932-fcb1e4a0-eb9d-4c51-bc78-82bf7e368887.png">
