### ISSUE TITLE
Fig 3: should we show proportion over which a node is coalescent

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#181]
In figs 5 and 6 we are shading nodes depending on what proportion of time the node is coalescent. This also applies to the pedigree figure, 3b, where (for example) node F is coalescent in the middle, but not from 0-2 and 7-10. This is pretty evident from the pedigree diagram (3a). Should we therefore show the nodes in fig 3b using the same scheme as in figs 5 and 6, or save the explanation for later?

**Comment by hyanwong** [comment]
The issue here is that we haven't talked about edges being sample-resolved, so perhaps it doesn't make much sense.

**Comment by jeromekelleher** [comment]
No, I'd keep this one simple. As you say, we haven't talked about sample resolution yet so wouldn't make sense.
