### ISSUE TITLE
Full sibs probably allowed in eARG encoding?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#182]
In the caption for Figure 5 we say 

> Note the complex full-sib relationship between B and C; this could not be directly represented in a Griffiths-like EARG encoding (see section XXX)

But actually I think we *can* represent a full sib relationship in an eARG, can't we? It looks basically the same, like this (breakpoints are x and y)
<img width="360" alt="Screenshot 2022-03-23 at 11 21 16" src="https://user-images.githubusercontent.com/4699014/159688313-39f39af1-0302-446b-8244-f0307ea436d4.png">

It's true that we can't model this in the CwR, because the 2 recombination events and the two coalescent events are simultaneous. And it's also true that you would probably want to model the generations as gamete-to-gamete like Hudson does, and therefore place the CA events in a previous generation to the RE events. But the eARG *encoding* does allow this, I think?

**Comment by jeromekelleher** [comment]
Yes, you're right I think. You'd have sample node -> RE node + breakpoint -> [parent 1, parent 2]
