### ISSUE TITLE
Time scales for Fig 6 plots

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#185]
It is unclear what the meaning of the Y axis is in Fig 6. In fact, at the moment it is arbitrary, chosen to give the clearest layout (KwARG and ARGweaver use the default graphviz.dot Y positioning, whereas Relate and tsinfer use the ranked node times).

We have 3 options for each plot: the graphviz dot layout, the ranked times, and the true ts times. Here's what they look like (ARGweaver has  *weird* true times: presumably because of discretisation: I'm not sure logging will help here)

-----------
## Default "dot" Y positions:
<img width="1059" alt="Screenshot 2022-03-24 at 11 58 38" src="https://user-images.githubusercontent.com/4699014/159911551-20c2003f-612e-47ba-aa27-e9b33a821de9.png">

-----------
## Ranked node times:
<img width="1073" alt="Screenshot 2022-03-24 at 11 57 35" src="https://user-images.githubusercontent.com/4699014/159911399-04da4f35-d8a6-4bb9-b39c-e930bef73910.png">

-----------

## True node times

<img width="759" alt="Screenshot 2022-03-24 at 12 03 57" src="https://user-images.githubusercontent.com/4699014/159912380-719c103a-5fb9-4629-81dc-f2e1e913ddea.png">

**Comment by jeromekelleher** [comment]
Hmm, ISWYM. The "True node times" is pretty nasty, so lets not use that (good to see what it looked like, though, thanks). I don't know otherwise.

**Comment by hyanwong** [comment]
#189 gives this, using the default dot about for Y times, and tweaking the X positions:

<img width="1245" alt="Screenshot 2022-03-27 at 15 51 52" src="https://user-images.githubusercontent.com/4699014/160287188-2d90603c-a3a0-4436-a764-c5d34ca981ab.png">
