### ISSUE TITLE
Hand-adjust the node X positions in figure 6

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#186]
There are a number of nodes in Fig 6 that could do with the X position hand-tweaking. For example, we could pull all the nodes from each tree in the JBOT to different X locations, which would emphasise the distinct trees. Also one of the tsinfer nodes in the penultimate timeslice is weirdly off-centre.

It might also be nice to have all the samples in the same order in all the plots, although we're not using this figure to compare how well each method does at inference, so perhaps that's not really necessary?

We could use the tweak_x parameter to `argutils.viz.draw` to do this, but it might be a bit of a faff. The best way would be to have some way of making the points interactive in jupyterbook, dragging them to the right position, then outputting the point positions to reuse, but I suspect that might be too involved to code up.

However we do it, we probably want to decide on https://github.com/tskit-dev/what-is-an-arg-paper/issues/185 first, as this will determine the layout that the "dot" engine produces, and hence how much tweaking is required.

**Comment by hyanwong** [comment]
I've just been trying this. Here's a re-working:
<img width="1245" alt="Screenshot 2022-03-27 at 15 51 52" src="https://user-images.githubusercontent.com/4699014/160287188-2d90603c-a3a0-4436-a764-c5d34ca981ab.png">

**Comment by jeromekelleher** [comment]
Very nice!
