### ISSUE TITLE
Add a CA-non-coalescent node to figure 5

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#193]
We probably want to discuss the fact that when going from fig 5b to fig 5c we also delete any nodes that are CA only but are not associated with any coalescence (i.e. the coalescence is in non ancestral material). There are no such nodes in the current figure. I've found that the easiest way to get nice diagrams is to repeatedly simulate with different seeds. Changing the results here would probably be a bit of a faff, but worth it, I guess?

**Comment by jeromekelleher** [comment]
Perhaps not worth getting in to - these types of event don't happen in the SMC, e.g., and there's probably already enough detail in fig 5. Up to you though.

**Comment by hyanwong** [comment]
I might see if any other seeds work. I think it is good to make the distinction in the text between a CA node and a coalescent region. Presumably we want to avoid the term "coalescent node" where we can. So this would be a graphical illustration of the point.
