### ISSUE TITLE
Revise "upward" and "downward" terminology

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#197]
In a few placed in the text we mention "upward(s)". In https://github.com/tskit-dev/what-is-an-arg-paper/pull/196#discussion_r843843722 Jere pointed out that "rootward" would be better, and I agree. Just a quick issue to remind ourselves to look at this.

**Comment by gregorgorjanc** [comment]
What about "backward(s)-in-time" - that is used in other places too? I also like "rootward"!

**Comment by petrelharp** [comment]
(just happened to notice this, and I Have an Opinion =): "longer ago" and "more recently", IMO!
