### ISSUE TITLE
ARG Inference methods section revision

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#199]
~~1. Remove the subsections
2. Condense things down to a few paragraphs.~~

~~No need to name all the methods, we just want a rough classification following existing structure. Basically one paragraph discussing the parsimony and hueristics, and one about model based methods. (Perhaps better to put the model sampling first, for clarity).~~ (now done)

Then some paragraphs discussing Fig 6. Things to say

1. They're all ARGs. 
2. Point out the "recombinant" nodes in Relate and tsinfer. Explain how Relate and tsinfer make ARG-like things in more detail.
4. In contrast kwarg and ARGweaver have exact recombination nodes.
5. We can see commonalities in these inferred structures, but there are also substantial differences. We have some quantitative information about the ARGs, which may be helpful for later comparison.
6. They're all ARGs and they're all represented using tskit succinct tree sequences here.

**Comment by a-ignatieva** [comment]
I will!
