### ISSUE TITLE
Fig 1 - should edges be a set?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#209]
When we describe edge annotations on Fig1, we say that the annotations for each edge can be a set of intervals. Do we want to therefore put the edge annotations in Fig1C in curly braces, e.g. `{(0,L]}`

**Comment by hyanwong** [comment]
Also, the column for the annotations in Fig 1C doesn't have a column name. Do we want to make one?

**Comment by jeromekelleher** [comment]
Technically yes - I left then braces out as I thought it might just obscure things. I don't have a strong feeling about it.
