### ISSUE TITLE
Suggestion for replacement fig 5

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#228]
We had decided to place what is now Fig 5 (Jere's nice plot) into an appendix (#221). If we would like another figure here, I think it would be useful to show a plot of how much space is devoted to different sorts of nodes in the "big arg" (Fig 3A) vs "little arg" (fig 3B with the top cut off) schemes, as the sample size increases. We can simulate this easily, since we have a big args simulator in this codebase. It would be interesting to know additional stuff like the relative number of CA-but-non-coalescent nodes, the relative number of nodes above the local roots to the grand MRCA, and the proportion of recombination nodes.

This could be an effective way to convince people (if they weren't 't convinced already) of the efficiency benefits of different sorts of encoding.

**Comment by jeromekelleher** [comment]
This would be quite a bit of work, and anyway the key fact is well known: a big ARG has O(e^rho) nodes whereas the little ARG as O(rho^2) nodes. Do we need to do any more convincing (other than making this point clearer)?

**Comment by hyanwong** [comment]
If it it likely to end up being a lot of work, then yes, I think we need to think hard about it. Regardless, we do need to make this point clearly.

I don't think there is any know pattern for the number of CA-but-not-coalescent vs the number of recombination nodes, etc, is there? How about the number above the local roots? I personally would find some sort of handle on this useful.

**Comment by jeromekelleher** [comment]
They're all non ancestral, they never show up in the trees. So, what's the point of studying them?

**Comment by jeromekelleher** [comment]
I think there's some confusion about what a big arg is here, which I guess underscores the need for a clear explanation

**Comment by hyanwong** [comment]
> They're all non ancestral, they never show up in the trees. So, what's the point of studying them?

I think I confused you with my terminology, sorry. I didn't just mean the unvisited "big ARG" nodes (e.g. Wiuf & Hein node j) but also the other nodes which are not (always) present in the Hudson ARG (e.g. node w, and possibly node k which does show up in some implementations but (I think) is culled from others)?

Re trees, we might well want to talk about nodes that are one or other form of ARG but are not relevant to the tree topology, or are otherwise undetectable, I think? There's certainly a good reason to talk about the number of nodes you expect that are present in super diamonds, etc? I think the number of non-ancestral nodes is interesting too, but perhaps you don't?
