### ISSUE TITLE
Modify tsdate usage

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#230]
On this line:

https://github.com/tskit-dev/what-is-an-arg-paper/blob/6727d92fc960a320197ab93554a2beb3e484f474/make_example_outputs.py#L45

We use tsdate simply to give a roughly reasonable time order to the nodes for the tsinferred ARG. The latest release of tsdate won't allow this, however, as it deliberately errors out when given a tree sequence with unary nodes. The [latest dev version](https://github.com/tskit-dev/tsdate/commit/dc72e0715b2d06aea4dff63355e120dc952694ce) allows us to work around that by overriding the error, like so:

```
priors = tsdate.build_prior_grid(tts, Ne=Ne, allow_unary=True)
tsdate.date(tts, mutation_rate=mu, priors=priors)
```

Once there has been a new point release of tsdate, we should update and re-run this code.

**Comment by hyanwong** [comment]
I just chatted to Nate about making a 0.1.6 tsdate point release (would also be useful for GEL analysis) and we came to the conclusion that it should be easy (the API is reasonably OK now). So I'll ask Ben if we can do that e.g. tomorrow and then we can also close this issue.

**Comment by jeromekelleher** [comment]
@hyanwong - I think we decided to just drop tsdate as the benefit was pretty marginal and it would be confusing to describe (so we can close?)

**Comment by hyanwong** [comment]
Yes, I have dropped it. I was planning to close with the PR doing that, but can close now just as easily.
