### ISSUE TITLE
High level structure, esp "event ARG" section (and dependency of gARG on edge annotations)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#247]
Jerome's recent changes are good, but I'm wondering if the "Node vs edge annotations" comes too late (i.e. after the discussion of the problems of eARGs). This is especially noticeable because Fig 1 describes node vs edge annotations, and we want to come across that figure ASAP. Also, I do think that some people imagine an eARG as an edge-encoded object (Alwyn, for example).

There's an interesting dependency here. You can have an eARG with edge or node annotations, but if you have a gARG, you *have* to have edge annotations, because there isn't such a thing as a "recombination node" any more, on which to pin breakpoint information.

I think we should introduce the node vs edge thing after talking about the order requirement of a node-annotated eARG, but *before* talking about limitations of classifying nodes according to a discrete set of events. The edge annotation change can then be something that "enables" the transition to a gARG. So I suggest that the sections should go

* Event ARGs
  Intro para
  * node vs edge annotation
    formal definition of node annotated eARG
    order dependency problem
    edge annotation as a solution (also allows some deviations from strict Griffiths model, e.g. multiple breakpoints)
  * Problems with eARGs
    tied to Griffith process:
    - cannot have events outside the that process (e.g. gene conversion, although this could be tracked in an edge-annotated version)
    - cannot have multiple RE/CA events at same time
* Genome ARGS
   allow arbitrary patterns of relationship
   can "condense" events into a single node (e.g. multiple coalescences)

Then we have 2 sets of topics (I'm unsure what order to take these in):

1. Precision, collapsing nodes, and simplification
2. Efficiency, sample resolving, and tree extraction / SPRs

The last section can be the round up of ARGs inferred by different methods, as it is at the moment.

**Comment by jeromekelleher** [comment]
Sounds reasonable. I'm currently working on a change that merges the discussion of fig 5 (different ARGs) into the precision section. It's quite boring and descriptive as it's own section, but if we use it as a way to illustrate the varying precision argument we can use it in a nice way.

Let's see how it works out after a bit more revision of the individual sections.

**Comment by hyanwong** [comment]
I'll work on the eARG node vs edge organization in a separate PR.

**Comment by jeromekelleher** [comment]
#249 is making widespread changes so I'd hold off on this, please.

I'm going through the whole document repeatedly trying to make the overall narrative work, and it's coming together.
