### ISSUE TITLE
Graphical representation of eARG vs gARG

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#250]
I’ve been trying to think how to illustrate (graphically) the difference between an eARG and a gARG, and come up with what could be a nice representation. We could draw an eARG without any node symbols, representing inheritance paths, and for gARGs, place node symbols representing the “instantiation” of a genome along that lineage. Then for the 2-re-node (recommended) version, we can place two adjacent circles, like this:

<img width="928" alt="Screenshot 2022-08-26 at 09 42 17" src="https://user-images.githubusercontent.com/4699014/186862481-f740a04a-2997-40dd-8fc8-85b4a6607c7a.png">

(also posted on slack)

**Comment by JereKoskela** [comment]
I'm not sure this adds clarity, at least to my way of thinking. The eARG data structure still has nodes, it's just that they correspond to events rather than genomes, right? In which case drawing it without nodes seems misleading.

I'm not sure there is much of a visual difference, given that the main thing that separates the two is the meaning ascribed to nodes. The way I would illustrate that would be along the lines we've already been doing: small examples of node and edge tables, and an accompanying discussion of the difference in interpretation. But it could be that I'm not being creative enough.

**Comment by hyanwong** [comment]
> I'm not sure this adds clarity, at least to my way of thinking. The eARG data structure still has nodes, it's just that they correspond to events rather than genomes, right? In which case drawing it without nodes seems misleading.

Thanks @JereKoskela. I take your points, but I think we would label the junction points with e.g. letters, to indicate that they are nodes on the graph. If we want to have node symbols on the eARG, I guess we could use different symbols. But it's nice to be able to take a gARG and remove the instantiated genomes, and be left with a graphical representation that makes some sort of sense. Perhaps I'm thinking of the gARG as representing a sort of "summary layer" on top of the paths of inheritance.

> I'm not sure there is much of a visual difference, given that the main thing that separates the two is the meaning ascribed to nodes. The way I would illustrate that would be along the lines we've already been doing: small examples of node and edge tables

I was trying to think of a way to illustrate (graphically) various ancestries without thinking about the exact mathematical (or tabular) way in which we encode them. So perhaps our aims are different here? This might not quite be the sort of thing to go in a paper, but I would find it helpful when e.g. giving a "popular" (!) talk on what we are doing.

I have further thoughts about the graphical representation too: I'll follow up with those in another comment.

**Comment by jeromekelleher** [comment]
Hmm, I'm tending to agree with @JereKoskela here - I feel like there is a lot of scope for confusing people here, and they'd get fixated on the nodes-vs-no-nodes difference between the first two diagrams.

It's also not clear to me where this goes in the manuscript - do you want to add another figure?

**Comment by hyanwong** [comment]
There are a few extra nicities with these viz possibilities (some might not be worth discussing in the paper, but I jot them down here for completeness)

1. You could imagine an edge-annotated eARG being extended to include GC events, which could be represented by an asymmetrical split into 2 lineages, like this: 
<img width="313" alt="Screenshot 2022-08-26 at 09 32 56" src="https://user-images.githubusercontent.com/4699014/186859590-4af4f22e-1155-4390-9746-69bde6cbed93.png">

2. The 2-RE version can be used to talk about why we recommend having 2 recombination nodes. I think (but I'm not sure: it's been a while since we talked about this) that the primary reason is to ensure that we are tracking 2 lineages at time t+epsilon. I think the discussion at https://github.com/tskit-dev/what-is-an-arg-paper/discussions/41#discussioncomment-2043115 focuses on why we want 2 nodes if we are storing breakpoints on nodes: it doesn't talk so much about what we want 2 RE nodes given that we are using an edge-annotated gARG.

3. A hidden agenda is that the black circles can represent genomes in cells. We can then
include larger (unfilled) circles that represent entire "individuals" (strictly, the haploid lineages within an individual). For example, polytomies in the gARG are essentially higher level summaries of events within cells. Like this:

<img width="440" alt="Screenshot 2022-08-26 at 10 08 41" src="https://user-images.githubusercontent.com/4699014/186869744-70b68424-e4a4-40dc-9357-339901020dc8.png">

**Comment by hyanwong** [comment]
> Hmm, I'm tending to agree with @JereKoskela here - I feel like there is a lot of scope for confusing people here, and they'd get fixated on the nodes-vs-no-nodes difference between the first two diagrams.

Yes, that's a fair point. Perhaps it doesn't belong in the manuscript. But I'd like to explore the visual representation so that I can use it when talking about the differences between eARGs and gARGs. Perhaps I should do this by having filled circles for events and unfilled circles for genomes? OTOH it is nice to show that you can "add" nodes anywhere along the lineages (e.g. creating a unary node) and that's still a valid gARG. Conversely, it's nice to be able to remove *all* the (genome) nodes and show that the path structure still forms a valid visual representation of the history. I guess that';s again because I'm not using this representation as a illustration of the *encoding*, but of the *biology*.

> It's also not clear to me where this goes in the manuscript - do you want to add another figure?

My preliminary thought was simply that we drop the node symbols (but keep the labels) from Fig 1, as that figure is all about events. We have node symbols (representing genomes) for all the other figures, as they are gARGs. If we want to discuss the 2-RE-node idea, we do it in an appendix. Something roughly like the "summary gARG" figure in my comment above could be used in the other appendix that talks about precision & cell lineages.

But I'm just throwing ideas around at this stage.

**Comment by hyanwong** [comment]
A tiny point is that the original Griffiths graphical plots don't have symbols for the nodes, so we would maintain consistency there. But on reflection, I think it would be equally reasonable to have a (slightly different) symbol for a node that represents an event to one that represents a genome.

FWIW, here are two alternative representations of the Wiuf and Hein plot, where I've put the two RE nodes together, to emphasise what we are doing, and to make it look a bit more like the original. I'm not sure if either of these is better than what we have at the moment, but I thought it worth a discussion (and to have them here for use in talks etc). Although the left hand plot looks neater and more like a "normal" ARG plot, it's unclear that the single line underneath each pair of recombination nodes is actually encoded by two edges in the tskit format.
<img width="571" alt="Screenshot 2022-08-26 at 10 31 22" src="https://user-images.githubusercontent.com/4699014/186874379-945aba43-1415-4f86-857f-a9c70a325633.png">

**Comment by JereKoskela** [comment]
Using different node symbols for the eARG and gARG sounds like a good way to do this to me. It emphasizes that the meanings of the nodes are different, without inviting confusion about whether the nodes are there at all.

If that's the approach we go with, then I'm not sure the original figure in this thread contributes much, given that the three ARGs will look very similar. But it looks like some of the other figures would be more distinct, and make for nice presentation resources. 

In the same vein, I'd prefer to keep some sort of node symbols in our Fig 1, but would be happy to have them be their own "event-node" symbol.

**Comment by hyanwong** [comment]
> Using different node symbols for the eARG and gARG sounds like a good way to do this to me. It emphasizes that the meanings of the nodes are different, without inviting confusion about whether the nodes are there at all.

Yes, on reflection I agree. What symbol might convey an "event" rather than a physical object, but is acceptable as a nodes symbol in a graph? A star seems a bit too cartoony, and I'd like to reserve squares for sample nodes, as in the standard tskit viz. Rounded square? upside-down triangle?

> If that's the approach we go with, then I'm not sure the original figure in this thread contributes much, given that the three ARGs will look very similar. 

For presentations, I think maybe the version without node symbols could be used to describe the biological relationships/inheritance pathways without any implication of how those relationships are encoded/tabulated. The version with "event" nodes shows a particular format for describing those pathways, focussed on modelled events, whereas a version with "genome" nodes shows the gARG format (either with 1 or 2 RE nodes).

> In the same vein, I'd prefer to keep some sort of node symbols in our Fig 1, but would be happy to have them be their own "event-node" symbol.

Agreed.
