### ISSUE TITLE
Break Fig 1A into two tables

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#251]
I think the current layout of Fig 1A is misleading:

![Screenshot from 2022-08-26 14-42-40](https://user-images.githubusercontent.com/2664569/186917290-4d3c0ff4-38df-45e3-9470-25ab0fb3935c.png)

This looks like we have a mapping from the node to two things, the breakpoint and an edge. This is incorrect, as we actually have a mapping from node to breakpoint plus and *unrelated* ordered list of edges. We need to show that the encoding consists of these two distinct things.

Particularly with 1C in mind, where a similar layout is used to show two things that are related (edges and intervals).

**Comment by hyanwong** [comment]
A good point. I agree that it should be two separate tables.
