### ISSUE TITLE
Incorporate Kuhner & Yamato's work 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#258]
I've had a quick look over [this paper](https://link.springer.com/article/10.1007/s00239-017-9786-8) and there's quite a lot or relevant and interesting stuff in here. We should at least mention it (for example, when talking about the difference between a series of trees, they call this the "interval-tree representation"), and update the methods overview to include refs to [LAMARC 2](https://academic.oup.com/bioinformatics/article/22/6/768/296494) (which is used here to generate a cloud of inferred ARGs)

**Comment by JereKoskela** [comment]
A minor nitpick which I'm bringing up because I've made the same mistake tons of times: It's Yamato, not Yamamoto.

**Comment by jeromekelleher** [comment]
Keeping this open as there's a few places we can ref them where we touch on things they cover
