### ISSUE TITLE
"Genome" terminology

### ISSUE THREAD

**Issue by a-ignatieva** [tskit-dev/what-is-an-arg-paper#259]
Just regarding phrasing (in the genome ARG section and maybe further on). I'm pretty sure "genome" usually refers to the full set of genetic material - so a+b in figure 1A for individual I1, for example. But we talk about recombination between genome a and genome b, and diploids having two genomes etc. Just wonder if genome is definitely the right word here! Or at least I think it'd be worth stating what we mean by genomes (unlinked genomic sections or something), as it's not standard usage.

**Comment by jeromekelleher** [comment]
This is something we've gone around at length in various places and we settled on "genome" as the least-bad option as there isn't a standard terminology for the thing we want to refer to. See the "tree sequences" section in the [msprime 1 paper](https://academic.oup.com/genetics/article/220/3/iyab229/6460344) for the final intended usage.

We may need to be clearer about this in the text though?
