### ISSUE TITLE
Parent-child vs ancestor-descendant terminology

### ISSUE THREAD

**Issue by gregorgorjanc** [tskit-dev/what-is-an-arg-paper#262]
Its unfortunate that parent-child has two meanings:
1) In a pedigree it refers to actual individuals and nodes in a pedigree graph
2) In a general graph it only refers to nodes, which can be actual parent-child nodes or nodes with a much more distant relationship (particularly after a simplification)

Should we use ancestor-descendant terminology to make it clearer?

However, ancestor-descendant can also be understood wrongly - as nodes with direct connection or as nodes there are connected by a path that passes through other nodes.

Any thoughts on this?

**Comment by jeromekelleher** [comment]
It is tricky - I agree that parent-child can be misunderstood, so I've been trying to use ancestor-descendant in new text. We should keep a close eye on the specific usages to see if there is the ambiguity you're talking about and clarify as necessary.
