### ISSUE TITLE
Error in big ARG discussion?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#273]
>The process then continues until there is only one lineage left (the Grand Most Recent Common Ancestor, GMRCA), which is guaranteed to happen in finite time because of the linear rate of coalescing vs. quadratic rate of branching

Isn't this the wrong way around @JereKoskela ? (Quadratic coalescing and linear splitting?)

**Comment by JereKoskela** [comment]
Well spotted, thanks. Simple case of proof-reading what I meant rather than what I actually wrote. I'll fix it.
