### ISSUE TITLE
Discussion point: point out that "The ARG" is the wrong way to think about this

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#279]
Something to mention in the discussion:

> We should stop saying "The" ARG and instead say "ARGs". It's a subtle point, but I think referring to a singular ARG is misleading because (a) there are a bunch of subtly but importantly different objects that we can call reasonably ARGs, and (b) even for a subclass of ARGs there will always be a very large number on ARG instances that are equally likely under whatever model you are using.

We should follow Griffiths' example: "An Ancestral Recombination Graph"

**Comment by hyanwong** [comment]
If we want a fuzzy term, or to avoid repetition, we can use either "an ancestry" or "a phylogeny" (or "recombinant phylogeny) too, as it's reasonably to think of both of those as reticulate. But "an ARG" is a more precise explanation of what we are doing.

**Comment by jeromekelleher** [comment]
Agreed, but that's not really the point of this issue. Just putting it in here so that we remember to add this specific point.

**Comment by hyanwong** [comment]
Yeah - I'm just sticking it in here because when we can bear it in mind as a potential replacement when we go though the text to check for accidental mentions of "the ARG".

**Comment by jeromekelleher** [comment]
After trying out we decided it's not worth getting into this, just seems pedantic.
