### ISSUE TITLE
Make explicit that we are *not* using Gusfield's definition

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#280]
In "Recombinametrics", Gusfield says

"*Definition*" An ancestral recombination graph, abbreviated ARG, is a genealogical network that obeys the additional restriction that _each site mutates at most once_; hence each site labels at most one edge of the networks."

He later (page 71) goes on to define an ARG as explicitly (recombination) node labelled.

Quite clearly, we do not stick by his definition, and we should point this out somewhere.

**Comment by hyanwong** [comment]
He also (page 72) defines P and S parents, to address the node-order problem associated with node-annotated ARGs. We could mention this, if we want.

**Comment by hyanwong** [comment]
The Gusfield ARG mentions sites because it is quite tightly tied in to the idea of finding e.g. the minARG. The tskit structure is independent of the definition of the states of the sites that are inherited through the genealogy. We should make this distinction clear (and argue that there is value in tracing the transmitted lineages regardless of the mutations that are passed through them.

A clear example is Gusfield's recommendation that recurrent mutations can be represented using double crossovers. This is technically true if you are only interested in representing the sample sequences, but it "invents" events which do not reflect the history of inheritance, simply because the focus is on the generated sequences rather than trying to represent the (true) ancestry.

**Comment by hyanwong** [comment]
We could say "msprime has shown that there is considerable value in divorcing the process of generating (neutral) mutations from the process of generating the genealogy (=ARG) itself..."

**Comment by jeromekelleher** [comment]
Good points, we should definitely try to clarify this.

I don't think we need to get into justifying decoupling the ancestral process from mutational processes - our readers will be well versed in coalescent theory and take this for granted as a good thing.

**Comment by jeromekelleher** [comment]
We should clarify this with a couple of sentences in the "History" section in the "There has also been substantial interest in formulating and answering fundamental " para

**Comment by jeromekelleher** [comment]
Where do we want to discuss Gusfield in the current version? We can mention him in the "example definitions" section, but only if it serves narrative purposes (which I don't think it does, now?)

**Comment by hyanwong** [comment]
A single sentence about this might find a place in the "Appendix C Survey of ARG inference methods" section, as ISTR that Gusfield's definition is based on inferability.

**Comment by hyanwong** [comment]
Here's his definition:

![GusfieldARG](https://github.com/tskit-dev/what-is-an-arg-paper/assets/4699014/3968778a-758e-4585-9a3f-71560d043b68)

**Comment by jeromekelleher** [comment]
Interesting, thanks. Hmm.

Quite a restrictive definition actually, seems especially odd to require a single root.

**Comment by jeromekelleher** [comment]
I don't think we need to get into the weeds with Gusfield's definition. It doesn't depart from Griffiths in any ways that are interesting enough for us to discuss (and nobody else uses his formulation)
