### ISSUE TITLE
Replace references to "unary nodes" to "unary regions"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#281]
The more I am using it, the more I think we need to row-back on the term "unary node" while we still can, and refer to unary regions (or alternative terminology).

**Comment by JereKoskela** [comment]
What about "marginally unary node", or words to that effect? Unariness is still a property of the node, not the whole region. We could reserve the term "unary node" for nodes which are unary on all marginal trees (which I guess we are unlikely to need).

**Comment by hyanwong** [comment]
> Unariness is still a property of the node

Is it? Often nodes will be unary in some genomic regions and not in others. I therefore don't think of this as a node property.

> (which I guess we are unlikely to need)

Aren't all recombination nodes in a full ARG unary-everywhere?

**Comment by hyanwong** [comment]
Actually, a graph theorist might also claim that there are nodes which are binary, but which are nevertheless unary in all trees. For example, a node could be unary everywhere, but switch to a different child in certain genomic regions. These would appear binary in the graph structure, right?

**Comment by JereKoskela** [comment]
> > Unariness is still a property of the node
> 
> Is it? Often nodes will be unary in some genomic regions and not in others. I therefore don't think of this as a node property. That is, assuming that by node we mean "node in the graph", not "node in the tree".

I was thinking of "node in the tree". That's what the "marginally" prefix was trying to convey: restrict attention to a marginal tree, and then look at the degree of nodes in that tree. I think that's more informative than "unary region", which sounds to me like the whole region is unary (and I'm not sure what that would mean). "locally-unary" or "region-unary" could be alternatives.

> > (which I guess we are unlikely to need)
> 
> Aren't all recombination nodes in a full ARG unary-everywhere?

Good point.

**Comment by jeromekelleher** [comment]
I don't find "unary regions" helpful (what's a region?), and have been trying to systematise on using "unary nodes in the local trees", or "nodes that are unary in the local trees". It's slightly more wordy, but at least its descriptive.

**Comment by hyanwong** [comment]
Can we think of any alternative to "region" then? I'm not set on the word "region", but I think we need to avoid the term, "unary node(s)", even if followed by the phrase "in the local trees". It has led to misunderstandings in the past. 

In other words, I think it is important to have one term for a node that is unary everywhere, and another for a node that is only unary somewhere. Perhaps we can discuss in person sometime?

**Comment by hyanwong** [comment]
Just to follow up here: we are being misled by thinking in terms of trees all the time. A graph theorist would look at the whole graph (with or without annotations) and be very confused if we describe any of the partially-unary nodes as "unary" in any way. I think we should be consistent with mathematical graph terminology where possible, otherwise it gets very confusing.

**Comment by hyanwong** [comment]
Just reading the paper that was sent to us, which I think illustrates my point. They talk about simplification "removing unary nodes in the marginal trees". But often I don't think the nodes themselves are removed, it's just the portions of the nodes which are unary that are removed.
