### ISSUE TITLE
Cite Hubisz M., Siepel A. (2020) 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#31]
Nice clear explanations, we should mention this paper.

Hubisz M., Siepel A. (2020) Inference of Ancestral Recombination Graphs Using ARGweaver. In: Dutheil J.Y. (eds) Statistical Population Genomics. Methods in Molecular Biology, vol 2090. Humana, New York, NY. https://doi.org/10.1007/978-1-0716-0199-0_10

**Comment by hyanwong** [comment]
It is really nicely written, isn't it.
