### ISSUE TITLE
eARG figure problem

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#311]
The eARG fig currently looks like this:
![Screenshot from 2023-09-14 14-11-23](https://github.com/tskit-dev/what-is-an-arg-paper/assets/2664569/8c0603c4-a7b2-4415-83e6-73d105bba5c7)

Was this an intentional update, and if so, what's it intended to look like ultimately?

**Comment by hyanwong** [comment]
No, I uncommented the extra gARG table (which was in before) but didn't have the time to fix the layout. I guess we can grab the old code? Or I can fiddle with the spacings?

**Comment by jeromekelleher** [comment]
Oh, I see, I thought you meant showing a picture with the edges annotated by the intervals.

**Comment by hyanwong** [comment]
> Oh, I see, I thought you meant showing a picture with the edges annotated by the intervals.

We could do that instead / as well? We could e.g. use colour and annotate the graph nodes with breakpoints in red, and the graph edges with intervals in blue (and then use red/blue in the two tables)?
