### ISSUE TITLE
Should Fig 3a ARG be node annotated?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#32]
The ARG in Fig 3a is edge annotated, because some nodes have > 2 parents. See eg nodes 18 and 19 here.

**edited** Also, there are many cases of multiple edges between the same parent and child.

This might confuse people - should we show this ARG as node annotated instead?

![ARG_recomb_node_deletion](https://user-images.githubusercontent.com/2664569/149373552-9c8ce534-9b9f-478d-98a2-11cc7b3dbe59.png)

I think we probably need some code to convert and display an edge annotated ARG vs a node annotated one anyway for figure 2?

**Comment by hyanwong** [comment]
Good point, although note that a node annotated ARG could have 3 parents (it's just the Griffiths representation that requires 2 parents only).

I don't think we want to get into node vs edge annotation in this figure, so we don't want to show what the annotation is. Nevertheless, I agree it's confusing, so maybe we just want to pick a different example bu using a different seed in msprime?

**Comment by jeromekelleher** [comment]
> Good point, although note that a node annotated ARG could have 3 parents (it's just the Griffiths representation that requires 2 parents only).

I don't think so, if we're assuming that the ARG is embedded in a diploid pedigree? (Which seems like a reasonable thing to ground it on?). That's the only information we're allowed, right - an edge is either present or not (denoting *some* genetic inheritance) and then a recomb node has two parents an annotation to say where the breakpoint(s) occured. But these can only be back and forth within the same pedigree individual (or its unrecombined ancestors).

> I don't think we want to get into node vs edge annotation in this figure, so we don't want to show what the annotation is. Nevertheless, I agree it's confusing, so maybe we just want to pick a different example by using a different seed in msprime?

It'll be hard to do I think, broken up edges will propagate upwards in nearly any non trivial example.

**Comment by jeromekelleher** [comment]
I'll see if I can make a function to create a true node annotated ARG from the msprime input.

**Comment by hyanwong** [comment]
> I don't think so, if we're assuming that the ARG is embedded in a diploid pedigree? 

Hmm, but we *could* annotate nodes in such a way as to specify which bit of the genome goes through which edge. In fact, we could devise a system to store the graph in Fig 3b as a node annotated graph. It's just that (a) if it's node-annotated it's technically more difficult to construct the trees and (b) the specific node annotation scheme proposed e.g. by Griffiths doesn't allow this.

> a recomb node has two parents and an annotation to say where the breakpoint(s) occured. But these can only be back and forth within the same pedigree individual (or its unrecombined ancestors).

But we could use a different annotation system on the nodes, not simply a set of breakpoint locations (see above). Or are we saying that by "node annotation" we mean only storing a single vector of breakpoints on a node? If so, isn't that being deliberately too restrictive?

But I do take your point about diploids. I don't quite understand, therefore, how the msprime `record_full_arg` process generates these recombination nodes with multiple parents?

**Comment by hyanwong** [comment]
Here, for example, is what you get with seed 107, which doesn't have the "triple parents" problem.

<img width="683" alt="Screenshot 2022-01-13 at 17 28 12" src="https://user-images.githubusercontent.com/4699014/149379317-193833b3-ed40-42fc-a223-8ba57a189a06.png">

**Comment by jeromekelleher** [comment]
Well OK, I'm sure you could come up with a way of placing annotations on nodes that would be equivalent to our edge annotations. That's not the point though, because nobody does this. When I say "node annotated ARG" I mean "A graph G=(N, E) and a mapping f:N->Reals which gives the breakpoints at which recombinations occur on those nodes." (N is a set of integers, and E is a set of integer tuples (u, v) such that u and v are in N, u != v). That's the classical definition of an ARG and since that's what people understand, that's where we should start by default.

So we cannot ever have have two edges going between the same parent and child. (I know you've been making the point about graphs vs multigraphs, but for mathematical/explanatory purposes things are much simpler if we just stick to a graph.) I'm not saying this visualisation here isn't totally great, it's just not quite what people would think of as an ARG, we should try to given them what they want.

**Comment by jeromekelleher** [comment]
I don't think the definition above is a straw man - the point is that we're storing breakpoints where they happen, rather than propagating the **effects** of those breakpoints through the graph.

**Comment by hyanwong** [comment]
> When I say "node annotated ARG" I mean "A graph G=(N, E) and a mapping f:N->Reals which gives the breakpoints at which recombinations occur on those nodes." (N is a set of integers, and E is a set of integer tuples (u, v) such that u and v are in N, u != v). That's the classical definition of an ARG and since that's what people understand, that's where we should start by default.

Yes, I agree that should be where we start by default, but I don't think we should restrict a "node annotated graph" to be this definition. I think that's a "Griffiths graph representation". Surely a "node annotated graph" is a superset of Griffiths graph? For example, your definition above doesn't include the (trivial) extension of having multiple breakpoints on each node (i.e. more than one recombination per meiosis), which surely anyone would argue is a "node annotated graph"?


> So we cannot ever have have two edges going between the same parent and child. (I know you've been making the point about graphs vs multigraphs, but for mathematical/explanatory purposes things are much simpler if we just stick to a graph.) I'm not saying this visualisation here isn't totally great, it's just not quite what people would think of as an ARG, we should try to given them what they want.

**Comment by hyanwong** [comment]
Either way, for this particular plot, I don't think we want to get into the node/edge distinction. We just want to show that you can get rid of recombination & CA-non-coalescent nodes, without losing the marginal trees.

**Comment by jeromekelleher** [comment]
> Yes, I agree that should be where we start by default, but I don't think we should restrict a "node annotated graph" to be this definition. I think that's a "Griffiths graph representation". Surely a "node annotated graph" is a superset of Griffiths graph? For example, your definition above doesn't include the (trivial) extension of having multiple breakpoints on each node (i.e. more than one recombination per meiosis), which surely anyone would argue is a "node annotated graph"?

OK, so maybe different terminology? Breakpoint annotated graph vs .... ancestral interval annotated?

> So a different example but without any nodes with >2 parents would be fine for this: we just don't want to confuse people.

It's deeper than that, we can't have any multi-edges either. All of the above examples in which two nodes (u, v) such that there exists more than one edge joining them. That'll definitely confuse people, if they're looking an expecting the (a) to be a "normal" ARG.

So then, perhaps we need a third "top" panel here, starting with the node annotated ARG, moving to the edge annotated ARG (this current fig A) and then to the version with no RE nodes?

**Comment by hyanwong** [comment]
> OK, so maybe different terminology? Breakpoint annotated graph vs .... ancestral interval annotated?

Yes, that's indeed a different distinction. But I do like the node/edge storage difference. In particular, I suspect that however you devise annotations on the nodes, you will have the problem of not being able to extract the trees without considering all the nodes in the tree (or more accurately, there's no efficient sort order for the nodes like there is for the edges). I think this is more fundamental than the idea of *what* you store on the nodes or edges.

> It's deeper than that, we can't have any multi-edges either. All of the above examples in which two nodes (u, v) such that there exists more than one edge joining them. That'll definitely confuse people, if they're looking an expecting the (a) to be a "normal" ARG.

Sorry, I don't follow here. I have the feeling I'm being stupid, but you can have "diamonds" in a normal ARG can't you? And these are usually shown by two separate lines linking the same two points. In fact, that's something I really *do* want to show, because a surprising number of events correspond to diamonds, and the loops are a good way to show them.

> So then, perhaps we need a third "top" panel here, starting with the node annotated ARG, moving to the edge annotated ARG (this current fig A) and then to the version with no RE nodes?

Again, I'm not following here, sorry. I feel we need a whiteboard!

**Comment by jeromekelleher** [comment]
Just to clear up some confusion here:

> It's deeper than that, we can't have any multi-edges either. All of the above examples in which two nodes (u, v) such that there exists more than one edge joining them. That'll definitely confuse people, if they're looking an expecting the (a) to be a "normal" ARG.

I realise I'm wrong here: if we want people to see recognisable ARG, then it has to contain diamonds. Then, by definition the graph is really a multigraph (since we have to edges between the same pair of nodes). So, I think we just note this parenthetically somewhere when we're doing definitions and move on.

**Comment by jeromekelleher** [comment]
Going to close this issue as its out of date now. The figure will be updated to use the new local ARG simulation code.
