### ISSUE TITLE
ARGON ARG format

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#327]
@hyanwong you've mentioned the ARGON ARG format in a few contexts, but I can't see any actual definitions of it in the paper (or supplement). Can you provide some links to published details, please?

**Comment by hyanwong** [comment]
Pier directed us to https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-023-01379-x/MediaObjects/41588_2023_1379_MOESM1_ESM.pdf (pages 3-5), and also said the following:

> The ARG representation we use in ARG-Needle is a modified version of the representation used in the ARGON simulator, which I wrote a while ago. We have a brief discussion about this on pages 3-5 of [Supplementary Note 1](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-023-01379-x/MediaObjects/41588_2023_1379_MOESM1_ESM.pdf) of our paper. Briefly, I suspect the formats used in ARGON and ARG-Needle are closely related to that of tskit, with a few differences in terms of where/how information is stored.
> 
> In ARGON a [block](https://github.com/pierpal/ARGON/blob/master/SRC/Block.java) is a piece of genetic material with start/end attributes as well as pointers to other parent/child blocks. [Individuals](https://github.com/pierpal/ARGON/blob/master/SRC/Individual.java) are collections of blocks. Blocks are broken by recombination (and by coalescence). This leads to the useful property that a block always has a fixed set of children, which creates a bit more fragmentation but allows O(1) access to children during traversal. Recombination events could be represented in the ARGON format, but they aren’t in practice since they don’t really matter for properties of the ARG that are analyzed. So, when a recombination is sampled in the DTWF simulation, blocks are split and the pointers of children nodes are assigned to the new parent nodes, without keeping track of the recombination event.
>
> The ARG-Needle format is quite similar to this, but it allows blocks (which I think we call nodes there) to have multiple children, which leads to a bit less fragmentation but O(logK) cost to pick the right set out of a block’s K children at a site during graph traversal. ARG-Needle also doesn’t infer/represent individuals but just blocks/nodes. In ARGON, positional information is stored on nodes/blocks and there is no explicit edge object, while in ARG-Needle, for convenience, I think we duplicate this information in both nodes and edges. Note that storing start/end information on blocks/nodes doesn’t preclude efficient traversal of the graph

**Comment by jeromekelleher** [comment]
OK, great. So the "block" is basically the same as shipilina et al's "edge", and Wilder et als "brick". I think we can just drop this into the discussion (it's in there somewhere at the moment)

We don't need to go into too much detail I think, especially not if there aren't detailed descriptions in a publication.

**Comment by hyanwong** [comment]
Yes (although I think it might be the same as shipilina et al.'s "haplotype block"?

The {"intervals" are essentially stored as the edges of the blocks, rather than placed on the edges.

**Comment by jeromekelleher** [comment]
I've been looking at this, and I don't see anything fundamental that's worth discussing. From the published description, the ARGneedle format is essentially a gARG (otherwise how would it support to- and from- tskit conversion?).

The ARGON format (which is not widely used) is basically storing haplotype blocks, which Wilder's paper showed can be derived efficiently from a gARG. Since the gARG is the fundamental thing we want to describe, I don't think there's much to note here, in the context of the paper.
