### ISSUE TITLE
SARGE conversion 

### ISSUE THREAD

**Issue by awohns** [tskit-dev/what-is-an-arg-paper#33]
I imagine it would be useful to have a means of converting genealogies inferred by sarge to the tree sequence format for the figure comparing the output of inference methods? I don't think this has been done by anyone (doesn't look like it's in the [sarge repo](https://github.com/nkschaefer/sarge)) so I'm happy to have a go at it.

**Comment by jeromekelleher** [comment]
Sounds good - can you paste in some information about the SARGE format (and maybe an example) here for discussion please?

**Comment by jeromekelleher** [comment]
@awohns - we discussed this the other day and I think the decision was that converting the SARGE output to an ARG would be too difficult, as they don't provide anything that's particularly ARG-like?

**Comment by awohns** [comment]
Sorry for the slow movement here @jeromekelleher. I just had a look through the supplementary methods and it looks like SARGE does, in fact, infer recombination nodes, so I'll have another go at converting their format. These two figures in particular are relevant:
![Screen Shot 2022-01-31 at 8 54 11 PM](https://user-images.githubusercontent.com/10664424/151902092-ceb94e9d-3b45-4b20-9c50-f1fdf5027cbd.png)
![Screen Shot 2022-01-31 at 8 54 06 PM](https://user-images.githubusercontent.com/10664424/151902098-038ced71-8a55-4c57-a0ce-cfcf0e4f6e35.png)

**Comment by awohns** [comment]
Ok, so making progress: the following lines run Sarge on a single tree from `mspms `

> mspms 100 1 --mutation-rate 1e-4 --population-size 1 10000 -T --random-seed 1 2 3 > testoutput.ms
> python2 utilities/ms2sarge_input.py -m testoutput.ms -o test_sarge_input --num_bases 100
> bin/sarge --sites test_sarge_input.sites --input test_sarge_input.geno.gz -o test_output_sarge 
> bin/index output.sarge seq:1-2 | bin/trees2newick -v output_test.haps > test_newick_output

I think the best plan here is to take two output files: newick tree and the `recomb` file:
> which is a tab separated file of chromosome, start position, end position, upstream clade, downstream clade, and moving clade.

and then make an ARG out of it with `tskit`

**Comment by jeromekelleher** [comment]
Sounds great @awohns! Are the internal nodes in the SARGE newick labelled? Sounds like we're going to be constructing a tree sequence then from (essentially) a set of edge diffs?

**Comment by awohns** [comment]
Here's output for a single tree, doesn't look like it internal nodes are labeled

> ((Human-1-1:0.22222,(Human-1-2:0.11111,Human-2-1:0):0.11111):0.77778,Human-2-2:1.00000):0.00000;

**Comment by jeromekelleher** [comment]
Hmmm - this really could be quite tricky. I bet there's internal assumptions about the ordering of nodes which are used to compute the source/dest of the clades. I wonder if time is better spent elsewhere, since we can only show so many methods anyway?

**Comment by awohns** [comment]
You're probably right. Just to close the loop, this is what the output looks like with multiple trees:

> ms 4 1 -t 10.04 -r 100.0 10 > outputms.txt
python2 utilities/ms2sarge_input.py -m outputms.txt -o test_sarge_input --num_bases 100
bin/sarge --sites test_sarge_input.sites --input test_sarge_input.geno.gz -o test_output_sarge
cat test_output_sarge | bin/trees2newick -v output_test.haps > test_newick_output

The newick tree output looks like this:
> seq     1       ((Human-1-2:0.50000,(Human-2-1:0,Human-2-2:0):0.00000):0.66667,Human-1-1:0.00000):0.00000;
seq     13      ((Human-1-2:0.50000,(Human-2-1:0,Human-2-2:0):0.00000):0.66667,Human-1-1:0.00000):0.00000;
seq     20      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     21      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     22      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     30      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     51      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     59      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     62      (Human-1-2:1.00000,((Human-2-1:0,Human-2-2:0):0.16667,Human-1-1:0.00000):0.90909):0.00000;
seq     63      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     69      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     70      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     74      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     75      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     79      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     92      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     95      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20000,Human-1-1:0.00000):0.88889):0.00000;
seq     98      ((Human-2-1:0,Human-2-2:0):1.00000,(Human-1-2:0.20005,Human-1-1:0.00000):0.88886):0.00000;

The "recombination" file looks like this:
> seq     13      20      1,2,3,  0,2,3,  2,3,
seq     62      63      0,2,3,  0,1,    0,
The columns are chromosome, start position, end position, upstream clade, downstream clade, and moving clade.

**Comment by jeromekelleher** [comment]
It was definitely helpful to get the information here @awohns, so thanks for that. Totally up to you whether you want to pursue getting the conversion to work.

**Comment by awohns** [comment]
I agree that it likely won't be very productive it will be to pursue this further, so I'm happy to leave it!
