### ISSUE TITLE
Add edge annotations to simplification figure?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#337]
From Gideon & Alex:

> Fig 4: Would it be possible to provide an annotated version of the ARG in panel A? Either in this figure or maybe in the supplement? I think it might be nice for readers to be able to scrutinize how the trees exactly knit together in the ARG and having these annotations would make that easier.

I guess adding a supplemental figure in which we annotate the edges of each of the ARGs would be possible? I think it would be too noisy to include in the fig.

What do you think @hyanwong?

**Comment by hyanwong** [comment]
A supplementary annotated edge figure would work well, I think.

**Comment by hyanwong** [comment]
Like this? 
![simplification_with_edges](https://github.com/tskit-dev/what-is-an-arg-paper/assets/4699014/89762062-57ae-4d1a-bb29-4c716e201742)

**Comment by hyanwong** [comment]
(It doesn't have the local tree in, obviously)

**Comment by jeromekelleher** [comment]
Nice!

**Comment by hyanwong** [comment]
Leaving this open until we actually write a supplementary

**Comment by jeromekelleher** [comment]
I don't think we'll have a separate supplement until much later in the process, certainly not before review. Let's just put it in as a figure at the end.
