### ISSUE TITLE
Add para on inferring precision about recomb to "Precision" section?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#339]
Comment from Gideon and Alex:

> The “Precision of recombination information” is very interesting. This may be outside of the scope of your paper, but I’m wondering if there is space to fit in a brief conversation about what the implications are for inferring these different levels of precision on recombination information. When would one want to infer an ARG with a program that attempts to reconstruct all recombination events (e.g., ARGweaver) vs. programs like tsinfer that infer less recombination information?

We could add a paragraph here about this, but it would need to combine with the current material in the Discussion about downstream applications. We could move that discussion stuff here, potentially.

**Comment by hyanwong** [comment]
If we are struggling to find space, could we place any thoughts on this into "Appendix C: Survey of ARG inference methods"?

**Comment by jeromekelleher** [comment]
I think we're covering this now in s9, going to close
