### ISSUE TITLE
Emphasise unary nodes in tsinfer output

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#353]
Somewhere we should say that unary nodes are a reality of current methods, and tsinfer really does output them. I guess we could explain this in the "precision of recombination" section, with a forward reference to the idea in the first place that we start talking about unary nodes.

**Comment by jeromekelleher** [comment]
See also #355

**Comment by hyanwong** [comment]
We now say (at the end of the unary nodes section) "Furthermore, several current ARG inference methods infer locally unary nodes (see section XXX)", so we do need to pick this point out somewhere. This could be done in the "precision of recombination" section, or (if we don't think it's really to do with recombinational precision), in appendix C

**Comment by hyanwong** [comment]
The new inference section says:

> Shading by coalescent span reveals that many non-recombinant (green) nodes are
> ``locally unary'' (see section \ref{sec-locally-unary-edges}). In other words,
> in some regions of the genome, these nodes are present in the ancestry but do
> not correspond to coalescence. As argued previously, this can provide potentially useful
> information about shared ancestry. Note however, that such unary segments are not inferred
> in the \relate\ ARG: other than the samples it has entirely solid nodes.

We don't specifically mention tsinfer in here, though. So we could add an extra sentence if desired?

**Comment by jeromekelleher** [comment]
Let's keep it open for now, there's a few places we can splice this is.

**Comment by jeromekelleher** [comment]
Done in #416
