### ISSUE TITLE
Remove "notebooks" dir

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#354]
The notebooks dir hasn't been touched in 2 years - simplest to just remove?

**Comment by hyanwong** [comment]
I have stuff in mine (for messing around purposes) that simply isn't synced. Easiest for me to leave it there for the moment and delete e.g. when we submit?

**Comment by jeromekelleher** [comment]
OK - but you could delete from repo and just keep in your own directory (i.e. not tracked by git?)

**Comment by hyanwong** [comment]
Yep, easy enough. I'm assuming that removing from git won't delete my personal copy (and I'll also add it to .gitignore, I suppose)

**Comment by hyanwong** [comment]
I guess it depends if we want people to see our "working".

**Comment by jeromekelleher** [comment]
It it's relevant to the final output and you want to document it, describing what everything is etc, then please keep it. Otherwise let's delete it from the repo. You just rename the directory in your working copy (or put it somewhere else; there's an infinite number of ways this can not be in git)
