### ISSUE TITLE
Unary nodes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#355]
We need to be really careful to explain unary nodes. The first time it's mentioned, spell out that tree nodes are the same nodes as the graph, but tree children is a subset of graph children. 

We want to emphasise that we can have unary graph nodes (e.g. fig 4 o). Some non-unary graph nodes can be unary in some of the local trees. 

Once we've explained all this, be careful to qualify with either "nodes that are unary in the local trees" or "locally unary nodes" as a shorthand (or similar)

**Comment by hyanwong** [comment]
I'm in the middle of a GitHub edit on this, FWIW. But I suspect it will tie in OK to whatever you write.

**Comment by hyanwong** [comment]
I think "locally-unary nodes" is clearest, and less misleading than "nodes that are unary in the local trees". The were "are" in the latter phrase implies that unaryness is a property of any node in general, rather than a property of a node-in-a-tree.

**Comment by jeromekelleher** [comment]
The disadvantage of just using that phrase "locally-unary nodes" is that it assumes that the reader understands what it means. Something a little more verbose like "nodes that are unary in one or more local trees", and mixing a few different ways of saying it will help the reader take this in.

Doing a global replacement of just saying "locally-unary nodes" will not help matters.

Go ahead and make the changes that you want, I'll be making updates afterwards. But, that's the rationale for not saying "locally-unary nodes" everywhere.

**Comment by hyanwong** [comment]
Yes, I agree with that. I think the phrase definitely needs defining up front before being used extensively.

**Comment by jeromekelleher** [comment]
So, not appropriate for use in captions, because people will read the captions before/without reading the text.

**Comment by hyanwong** [comment]
Possibly so. We already have a legend that talks about "percentage of node which is coalescent", though, so we may have shot the bolt on that one.

**Comment by jeromekelleher** [comment]
I'm going to close this as handled now, as we seem to agree that a section on unary nodes is the way to go. Some fine tuning is needed, of course
