### ISSUE TITLE
Comments from Andrew Vaughan

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#365]
Below some points to tick off. When these are done (or added as tracked edits to the overleaf), I will tick them off (or if not relevant, I will comment below)

- [x] At line 59, it is stated that the set of nodes of a gARG are represented by a subset of the natural numbers. However, the set of nodes in Figure 1 are instead represented by lowercase letters. The connection between them is clear from context, but maybe this connection should be made more explicit.
- [x] I really like Figure 1 in terms of thinking about an ARG explicitly embedded in a pedigree, but I think colors need to be more effectively utilized and/or some of the shades of the gray need to be made darker. The light gray pedigree structure with the D_1 to D_8 labeling is quite difficult to see, and it didn't show up at all when I printed this paper to edit.
- [x] I found the section "Prospective vs retrospective ARGs" to be rather confusing. In particular, the sentences "Event ARGs are defined in terms of the events that occur in the history of some set of sampled sequences. For example, Fig. 1 is ..." confused me because Figure 1 represents a genome ARG, not an event ARG. I felt that this interfered with my understanding of the contrast between prospective and retrospective ARGs and how they related to gARGs and eARGs.
- [x]  I thought that the phrase "as it allows to efficiently subset ARGs" in line 167 to be awkward phrasing.
- [x]  I assume you'll replace the AND OTHERS in the citations in line 210.
- [x] Should there maybe be a comma between pi_1 and pi_2 in line 213?
- [x] In line 220, the phrase "we an find edge" is a typo. Is it "can find"?
- [x] In line 233-235, I found it confusing to reference part D of Figure 4 before Figure 4 is introduced in the following section.
- [x]  Figure 4 is trying to make a really good point, but I don't think it communicates the ARG simplification procedure as well as it could. In particular:
  - [x]  (a) How the graph in part A is generated is somewhat glossed over. It's mentioned that it's a backward-time Wright-Fisher model, but why does that lead to the structure seen in A? For example, we see node i has only one parent and one child, while node e has two parents and two children. This is not classically possible under the event-based formulation of the ARG (which uses continuous time), which is the only data-generating process for generating an ARG that is discussed in this manuscript.
  - [x]  (b) I think it's confusing how the same letters are used to refer to different nodes. For example, node h is simplified out from A to B. Then, another node reappears in C that has the label h. From B to C and then again from C to D, it appears that the node labeled e shuffles back and forth between two locations on the ARG. I think that it's really important to be precise about what nodes are being removed, being combined, etc. and I think part of this could be cleared up by keeping node labels for nodes that persist and creating new labels when new nodes are formed from old ones.
  - [x] (c) I think colors and shading could be used more effectively. I don't think that the thickness of the edges of the ARG is an important point, so I would leave them all the same thickness. I also don't think the shading of nodes according to the span over which they are coalescent is an important point, so I wouldn't keep the node shading. Maybe the node outlines could denote the number of parents and nodes are shaded if they will be removed in the following step? I feel like the main point is in how the topology changes, so I would try to emphasize that as much as possible. Also, through either explicit labeling of the breakpoints in the ARG or through some color-matching of the nodes of the graph to the numbers along the sequence, it might be nice if you could see which nodes on the ARGs correspond to which breakpoints along the sequence.
- [x] At line 295, when it says "more than two parents (eg node e)", do you mean "more than two children (eg node e)"?
   - No, we do mean what is written
- [x] I think Figure 5 is fairly confusing for a few reasons. The leaf node ordering differs between the methods. The lines below each ARG (the genomic intervals associated with edges?) are not comprehensible, especially because many lines have the same color. At line 351, when you say "We can see, for example, that the Relate trees “share” less topology than other methods" I don't think it is clear why Relate is the outlier here. Once again, the fact that the leaf nodes are in a different order with each method makes a straightforward visual comparison between methods quite difficult.
- [x] I think Figure 6 makes a very important point, but I think there's an error. First of all, it might be helpful to specify the ordering of the recombination breakpoints along the genome. I realize that they are indexed alphabetically in time, but maybe explicitly stating 0<v<y<w<x<m would be helpful for comprehension. Anyways, assuming that's the correct ordering, we look at the two lineages left at time T: {(x,m,1)} and {(w,m,2)}. Conceptually, this can't be the case, because a common ancestor event between these two lineages would still leave an uncoalesced (w,m) segment. Concretely, the (w,x) segment from the leftmost sample goes missing. At event b, we have {(v,x,1)} and {(0,w,2)} having a common ancestor event to produce {(0,v,2)} but I think it should produce {(0,v,2), (w,x,1)}, right? If this is the case, the RE column and part B would need to be adjusted accordingly.

**Comment by jeromekelleher** [comment]
These have all been addressed, closing.
