### ISSUE TITLE
Terminology: refer to "coalescent points" not "coalescent nodes"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#37]
I just realised, when discussing https://github.com/tskit-dev/tskit/discussions/2089, that we should aim to avoid the term "coalescent node", because a single node can be a coalescent point in one tree but a unary node in another. I think we should use the term "coalescent point" where possible.

We can close this issue when we have gone through the (final) draft manuscript and checked on our terminology.

Note that I think we have a way of referring to each *edge* in each tree (I call this a "branch": i.e. multiple identical branches in adjacent trees may correspond to a single tree sequence edge). But we don't have a terminology to refer to each *node* in a tree (i.e. we don't have an X such that we say "multiple  identical Xs in trees along the sequence correspond to the same node).

**Comment by jeromekelleher** [comment]
I agree it's confusing, but I'm not sure "point" adds much clarity here. That has a spatial connotation to me, and implies either the geographical or genome coordinates at which a coalescence occured. 

I also use the "edge-vs-branch" shorthand for distinguishing edges in a tree from tree sequence edges. Maybe we should do something similar for nodes? Say, we have graph "vertices" vs tree nodes (or the other way around, I don't think it matters much)?

**Comment by hyanwong** [comment]
Yep, that works too. Given that we have a "node table", I guess we should use "vertices" for the tree version. I don't much like the word itself, but ISWYM about "point" being mistaken for a genomic location (we do often use the word in this sense). "Branch point" is more specific, and colloquial, but probably doesn't correspond to a unary node in most people's mind. I'm uncertain here, but either way, I think we will need to read through the text with this general issue in mind, so perhaps I should keep it open until then.

**Comment by jeromekelleher** [comment]
I'm going to close this - I don't think we'll end up with this terminology. "Node" is too fundamental here. If we have some specific text in the paper that we want to discuss and alter, then let's open another issue.
