### ISSUE TITLE
Cite GeL paper

### ISSUE THREAD

**Issue by gregorgorjanc** [tskit-dev/what-is-an-arg-paper#382]
We have a `TODO cite GeL paper` somewhere in the text.

If you point me to the DOI/website I can create BibTeX entry for this GeL paper and squash the TODO;)

**Comment by jeromekelleher** [comment]
I don't know what the right citation is - anyone know what paper to cite to describe the genomic dataset?

**Comment by gregorgorjanc** [comment]
I found this https://www.genomicsengland.co.uk/research/publications/publication-policy, which suggests citing:

```
The National Genomics Research Library v5.1, Genomics England. doi:10.6084/m9.figshare.4530893/7. 2020.
```

Though the DOI does not work:( - tried without the pesky space after `7.` and without the final dot but no luck:(

Will e-mail the listed contact `gecip-help@genomicsengland.co.uk`;)

**Comment by jeromekelleher** [comment]
Hmm, there's definitely papers to cite as well though. @hyanwong is in regular contact with some gel people, perhaps he could find out?

**Comment by hyanwong** [comment]
Sam Tallman says

> Hmmm - I’m not actually sure what the best citation is. There isn’t really one paper that describes/introduces the dataset in full, but I think this one is widely cited: [https://pubmed.n](https://pubmed.ncbi.nlm.nih.gov/29691228/)

**Comment by hyanwong** [comment]
I've used the one Sam recommended.
