### ISSUE TITLE
Add details on inference methods for fig

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#388]
We have no real detail on how the example ARGs fig was generated. Things to address

- Details of the dataset (how many sites, etc, where did we get it?)
- Version numbers of programs?
- What we did to the outputs to turn into tskit gARGs?

This can go in its own paragraph.

Comment from @gregorgorjanc:

> We should say how this figure was obtained  - I mean, software was run, but every tool produces something different so what was done to represent a comparable gARG figure across methods?

**Comment by hyanwong** [comment]
I guess I wrote most of the code for this, so it's easiest for me to write this para.

**Comment by hyanwong** [comment]
Mostly fixed in #398 - remainder to do in #399
