### ISSUE TITLE
Tsinfer figure is without "root breaking"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#390]
I just realised that the tsinfer figure shows the "old" tsinfer behaviour, in which the ultimate ancestor is not broken into pieces. Breaking the root up like this is now the default. So should we show it? The plot would then look something like this:

<img width="460" alt="Screenshot 2023-10-16 at 13 42 35" src="https://github.com/tskit-dev/what-is-an-arg-paper/assets/4699014/367cf095-a299-43a5-9b2b-aecd713a64e9">

To compare, this is what it looks like at the moment:

<img width="383" alt="Screenshot 2023-10-16 at 13 46 06" src="https://github.com/tskit-dev/what-is-an-arg-paper/assets/4699014/57e9d439-91ce-43f6-9055-65a28574e26d">

**Comment by hyanwong** [comment]
The colour scheme doesn't *quite* highlight the local roots in KwARG (A) and ARGweaver (B), because local roots are inferred to have ancestors that connect them to the grand MRCA.

**Comment by jeromekelleher** [comment]
Let's go with recent version, after discussion

**Comment by hyanwong** [comment]
Fixed in #398
