### ISSUE TITLE
Placement of the ref to Lewanski

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#400]
At the moment, we place "See Lewanski et al. (2023) for a biologically oriented introduction to ARGs." at the end of the first para, but to me it feels rather shoehorned in (perhaps that's just because I know it was added later).

As an alternative, we could even cite this in the first or second sentences, e.g. 

> Estimating the genetic genealogy of a set of genome sequences under the influence of recombination, 2 usually known as an Ancestral Recombination Graph (ARG), is a long-standing goal in genetics (see Lewanski et al. (2023) for a recent summary).

or

> Estimating the genetic genealogy of a set of genome sequences under the influence of recombination, usually known as an Ancestral Recombination Graph (ARG), is a long-standing goal in genetics. Broadly speaking, an ARG describes the different paths of genetic inheritance caused by recombination, and encodes a sequence of correlated genealogical trees along the genome (see Lewanski et al. (2023) for a recent summary)

Is either any better, or are they both just as awkward?

Opening this as an issue because I don't want to make a semi-important change like this in an overleaf edit

**Comment by jeromekelleher** [comment]
Eithers good I think, pick your favourite

**Comment by hyanwong** [comment]
I changed the wording from "See XXX" and now I think it reads fine.
