### ISSUE TITLE
Clarify or remove Relate description

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#402]
At the end of section 5 we currently say:

> Relate first infers local tree topologies, and then identifies edges that persist from tree to tree by reasoning about the sets of samples subtended

But I think @a-ignatieva said this was misleading. Do we want to rephrase or (partially) omit anything here?

**Comment by jeromekelleher** [comment]
Yes, let's keep this open for a bit to track.

I need to make a heavy edit pass to the second half of the paper yet, will take this into account (we talk about how relate does things in a few places now, want to dedupe)

**Comment by jeromekelleher** [comment]
Closed in #406. We're just talking about Espalier here as an illustration of the overall strategy
