### ISSUE TITLE
Mention that eARG recombination nodes are (by definition) unary

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#411]
It would be useful to point out in section 5 that recombination nodes (as defined when converting from e.g. fig 3A to fig 3B) always have only one child (i.e. are never coalescent), which is one reason that keeping such nodes in the local trees is important (otherwise all information associated with recombination precision is lost). There is an obvious place to put this around line 260, in the "ARGs and local trees" section, before getting into the locally unary section. I'll put a comment on overleaf.

**Comment by jeromekelleher** [comment]
done
