### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/what-is-an-arg-paper#424]
Looks *great*. A few minor comments:

Line numbers refer to `b555b2c2042d0fd6bb5095b9f6dd5edcf5d2ef8c`.
- l.31: Sentence starting "The UK Biobank..." is I think missing a word or two?
- I love "pastwards"
- you might clarify somewhere whether you want everyone to henceforth say gARG or eARG or if it's fine if people continue saying just ARG?
- l.279: missing a ")" in the definition of E^x
- "more information than the series of tree sequences along the genome": perhaps edit this to make the quote less weird? "more information than the series of tree[s]... along the genome"
- l.501: you've got some ~s that were supposed to be non-breaking spaces
- l.708: floating "(Section 10"

**Comment by jeromekelleher** [comment]
Thanks Peter!

- We've tried to convey that the term ARG is good for general use, and only use "gARG" when its actually important. I added a comment "(here, and throughout, we use the general term ``ARG'' when the details of the specific encoding are not important)." in the Ancestral material section, which will hopefully clarify. There's also a comment to this effect in the discussion.
- The quote thing is really tricky. Their terminology is so confusing that I don't think there's much we can do about it - edits like you suggest would be very close to changing the actual text.

I've added you to the Ack'ed for helpful comments, just FYI
