### ISSUE TITLE
confusing over-use of "true"

### ISSUE THREAD

**Issue by castedo** [tskit-dev/what-is-an-arg-paper#440]
I did find this confusing after reading "true" three times.

https://github.com/tskit-dev/what-is-an-arg-paper/blob/55986e675fdd2db3bf1687e0ac75e107c67b318b/paper.tex#L154-L158

When I read the first "true" i thought the "population" ARG was in contrast to the "true", but then "population" ARG is defined as also true. And then the 3rd mention of true seems to clarify that the first use of "true" is not the definition of a "true" ARG.

Perhaps rather than trying to use diff adjectives to ARG, just rephrase the whole thing to say an ARG can be relative to an entire population or just a sample. And separately you can point out that a "true" ARG has a bunch of unknowable detail.

**Comment by jeromekelleher** [comment]
Well, there's a whole story behind this, in which we're trying to alleviate some confusion that Nick Barton had. He thinks of an ARG as the "true" ARG, so we had to try and pick apart what that means. We did have extended discussions on this one, and I think it's inevitable that there'll be some confusion about it (since it is a very confusing topic!)

**Comment by castedo** [comment]
Maybe what I find confusing is the introduction of "true" and "population" in the same sentence right after saying "subtly different concepts ... to distinguish". At first read I thought you are distinguishing "population" ARG VS "true" ARG, as though those are two concepts to distinguish against each other.

Whereas perhaps what you mean is there are two distinctions: 1) "sample" ARG vs "population ARG" and 2) "true" ARG vs simplified/summarized/reconstituted/fake ARG.

**Comment by jeromekelleher** [comment]
This passage has been cut now.
