### ISSUE TITLE
colinear sequences vs shared genome coordinate space

### ISSUE THREAD

**Issue by castedo** [tskit-dev/what-is-an-arg-paper#441]
When I read "colinear sequences" here:

https://github.com/tskit-dev/what-is-an-arg-paper/blob/55986e675fdd2db3bf1687e0ac75e107c67b318b/paper.tex#L1571

I guessed that it means matching genome coordinates, like here:

https://github.com/tskit-dev/what-is-an-arg-paper/blob/55986e675fdd2db3bf1687e0ac75e107c67b318b/paper.tex#L303-L304

Assuming I understand "colinear" correctly, perhaps it will help some readers to use the genome coordinate language in both places or the opposite if I'm weird for not knowing "colinear".

**Comment by jeromekelleher** [comment]
I'm not sure where I picked up "colinear", but it does seem quite apt: https://en.wikipedia.org/wiki/Collinearity

I guess the point in this early sentence was to try and say the same thing more concisely, without getting bogged down on detail.

**Comment by jeromekelleher** [comment]
I  think the current text is good - using different words to explain a critical concept like this seems reasonable.
