### ISSUE TITLE
Something messed up with figure refs in Appendix D

### ISSUE THREAD

**Issue by castedo** [tskit-dev/what-is-an-arg-paper#443]
The figure referenced by the following line does not seem to be the intended figure:

https://github.com/tskit-dev/what-is-an-arg-paper/blob/55986e675fdd2db3bf1687e0ac75e107c67b318b/paper.tex#L2457

If it is intended, I'm confused by how the figure relates to the textual description.

**Comment by jeromekelleher** [comment]
Aha, well spotted! This is a bug, thanks.
