### ISSUE TITLE
Move python code to subdir

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#5]
We'll probably end up with a good few scripts, and the top-level directory ends up being busy enough with the latex stuff.

Can we move all the code into a ``scripts`` or ``src`` directory or something? (Assumed to be executed from the root, as necessary?)

**Comment by hyanwong** [comment]
Yeah, although what I've stuck there aren't scripts, they are routines used in multiple scripts (e.g. for importing AGRs into networkx, etc). Should we stick them in e.g. `utils` or `modules` or something?

**Comment by jeromekelleher** [comment]
``utils`` sounds good. I guess it'll be a package then (with an ``__init__.py``), so maybe ``argutils`` would be a good name?

**Comment by hyanwong** [comment]
I have 4 separate files ("packages") in there. Not sure if we want to roll them into one? They do quite different things

* argdraw.py: routines for drawing a networkx graph in ts ARG-style
* constants.py: defines e.g. NODE_IS_RECOMB
* convert.py: convert e.g. ARGweaver files to tree sequences (could also do other conversions in there)
* ts_process.py: e.g. convert msprime old style args to the new style, various general utils for manipulating tree sequences
