### ISSUE TITLE
Figure 1: Hudson's alg vs Big ARG

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#55]
We'd like a figure showing the differences in the state space between Hudson's algorithm and the Big ARG. Hudson's algorithm should show the full state, include the (left, right, ancestral_to) tuples that are associated with each lineage.

The ``arg_sim`` function might be helpful for inspiration [here](https://github.com/tskit-dev/what-is-an-arg-paper/blob/7fb73720d63e930c25c29068367c428db069adf1/utils/args.py#L203)

@JereKoskela - are you happy picking this one up?

**Comment by JereKoskela** [comment]
[hudson_vs_bigARG.pdf](https://github.com/tskit-dev/what-is-an-arg-paper/files/8018485/hudson_vs_bigARG.pdf)

Here is a draft of the Hudson half of the picture. Open to comments before I draw a big ARG picture. It will be the same, except with less labelling throughout, with a simpler extant material column, and with a few more non-ancestral events thrown in.

The figure caption is a draft I've been updating as I draw the diagram. I imagine some of it may end up cut, or moved into main text.

**Comment by jeromekelleher** [comment]
![figure](https://user-images.githubusercontent.com/2664569/152961553-2f83a6dd-9d2f-461b-8531-e01ab8daeb9d.png)

**Comment by hyanwong** [comment]
This looks lovely.

**Comment by jeromekelleher** [comment]
Perhaps we should use set notation to show the set of intervals on an edge, so the edge joining K to M would have "{[0, x), [y,L)}; 1`` on it?

For simpler edges we'd have "{[0, L)}; 1" then? It's a lot of brackets all right though.

**Comment by hyanwong** [comment]
It would be nice to indicate the _x_, _y_ and _z_ breakpoints graphically, somehow. It's reasonably obvious for _x_ and _z_, but took me a while to figure out _y_

**Comment by hyanwong** [comment]
In our terminology, the "recombinant" nodes are A, F, D, and K, right?

**Comment by JereKoskela** [comment]
> Perhaps we should use set notation to show the set of intervals on an edge, so the edge joining K to M would have "{[0, x), [y,L)}; 1`` on it?

I tried this, and the extra brackets made the figure quite even busier than it already is. The semicolon is definitely a good idea. I'll give the brackets another go, maybe along with downscaling the size of the edge annotations a little bit.

> It would be nice to indicate the x, y and z breakpoints graphically, somehow. It's reasonably obvious for x and z, but took me a while to figure out y

Good idea. Maybe I should label the breakpoint on the cartoon chromosomes on each recombinant child node (x on A, y on F etc.). That would be consistent with the terminology of calling them recombinants.

> In our terminology, the "recombinant" nodes are A, F, D, and K, right?

Yes.

I'm getting a sense that we're happy enough with the overall graph for me to make a start on the big ARG too. None of these labelling details will be important for that.

**Comment by jeromekelleher** [comment]
No, the graph is great Jere - just nitpicking the details here.

**Comment by hyanwong** [comment]
Yep, this is a great topology layout (and the minimum to show non ancestral "trapped" recombinations, right?)

**Comment by JereKoskela** [comment]
> Yep, this is a great topology layout (and the minimum to show non ancestral "trapped" recombinations, right?)

Essentially yes. The A - E - F - I - J - K - M - N subgraph is the minimum if that was all we wanted to show.

**Comment by JereKoskela** [comment]
![Screenshot_20220208_141228](https://user-images.githubusercontent.com/6280602/153004215-c454dfb7-9d8b-4590-aeb3-7ca0aa04f693.png)

I added brackets and breakpoints, and made things a bit less dense by slightly reducing the sizes of node labels and edge annotations, as well as being more flexible about whether they are to the left or right of each edge. I don't think that has added any ambiguity, but it has definitely added white space.

Also included is a big ARG with one extra recombination, one extra merger, and one instance of lineage not getting cut once its material is all fully coalesced.

**Comment by hyanwong** [comment]
Great work @JereKoskela. It looks lovely. I wonder if in the caption we should mention that the extra nodes are P, Q, R (or even colour them differently in the big ARG figure). Similarly, should we label the extra recombination (_w_?) so that we can say that, since it happens in non-ancestral material, it does not affect the little ARG.

**Comment by hyanwong** [comment]
Actually, I see that the recombination in the trapped segment isn't labelled either. So maybe we should use v, w, x, y, z for the breakpoints? Or a, b, c, d, e, I suppose, if we think that lowercase letters won't get confused with uppercase ones.

**Comment by jeromekelleher** [comment]
This is great - I'd say let's PR it in and we can fiddle with the details in follow ups after doing a bit of writing around it?

**Comment by JereKoskela** [comment]
What's the best way to PR this @jeromekelleher? Do I push my .tex source file into the Illustrations folder, or something different?

**Comment by jeromekelleher** [comment]
Just put the tex directly into paper.tex and and open a PR? Don't worry if it's big and ugly.
