### ISSUE TITLE
Figure 4: genome coordinate annotations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#56]
We want a figure showing how the implicit genome coordinate annotations that we use in our ARG encoding (each recombination event with child u and breakpoint x has two parents, v and w, and we record edges (-inf, x, v, u), (x, inf, w, u)) is resolved to fully explicit edges via a variant of Hudson's algorithm. 

Panel A is an ARG encoded in the form above, and panel B is the fully resolved equivalent.

@a-ignatieva - are you happy picking this one up?

**Comment by a-ignatieva** [comment]
Yep, leave it with me!

**Comment by a-ignatieva** [comment]
How's something like this? Left is implicit coordinates, boxes hopefully show that the breakpoints are "local". Right is explicit coordinates, green is bits of the genome that have reached mrca.
![drawing](https://user-images.githubusercontent.com/36134434/152687482-7dcc64ee-b72e-47f3-8b07-83f7bb995040.svg)

**Comment by hyanwong** [comment]
Nice. I like it. It would be good to have some terminology to distinguish between these two forms (did we decide on implicit vs explicit?). See https://github.com/tskit-dev/what-is-an-arg-paper/discussions/23#discussioncomment-2120250

**Comment by jeromekelleher** [comment]
This is really excellent, thanks @a-ignatieva! There's a few things we need to sort out terminology and notation-wise (mainly the infinities), so let's not finalise it yet. I'll get back with some concrete suggestions once we've figured that out.

Another thing to consider is that what we're producing is very like Fig 1 in "Recombination as a point process", which we should acknowledge. I'll reproduce here for convenience:

![HUD](https://user-images.githubusercontent.com/2664569/152767158-6e387f6e-454c-4558-9d94-0128d121c318.png)

**Comment by jeromekelleher** [comment]
We could just reuse the example and recast it in our new notation? It's a great example!

**Comment by jeromekelleher** [comment]
See #64 for code to produce the wh99 ARG.

**Comment by jeromekelleher** [comment]
That's true - let's hold off a bit until we've figured out the inf-vs-0/L issue.

**Comment by hyanwong** [comment]
To pick up a point in https://github.com/tskit-dev/what-is-an-arg-paper/pull/85#issuecomment-1036066898, we could possibly use line width or intensity (alpha values?) to show the span of the edges?

We also need to revise this to use `0/L` rather than `inf`. I'm happy to do that if @a-ignatieva is busy

**Comment by jeromekelleher** [comment]
There's quite a bit of overlap in the information shown by figs 1 and 2 now with this, so I wouldn't spend any time on it until we have a good draft of those earlier sections and know what we need to display/discuss.

**Comment by jeromekelleher** [comment]
This is great @a-ignatieva and is *almost* right. 

I think we should think of the left-hand picture as showing what interval of genome ``parent`` transmitted to ``child`` (so, for example, edge (5, 8) would be [0, 10)). So, the edges denote inheritance down the graph (we could even put in arrows on the edges, to emphasise this?)

I guess then the T shape we have for showing recombinations isn't great then - maybe we should use a more standard graph layout, with individual lines between, .e.g, (0, 2) and (0, 3)

Likewise then for the right picture, we use the same edge layout, but show the flow of ancestral material from the bottom up and the coalescences, like you've done.

It would be useful to label them (A) and (B) also.

What do you think?

**Comment by hyanwong** [comment]
Do we want to show the equivalent trees, with "hanging topology" that gets pruned off by running the simplification/Hudson algorithm on the implicit version?

Also, do we want to actually use the Wiuf & Hein example here? We do have it coded up, and I don't think we are now using it anywhere else?

**Comment by hyanwong** [comment]
> I guess then the T shape we have for showing recombinations isn't great then - maybe we should use a more standard graph layout, with individual lines between, .e.g, (0, 2) and (0, 3)

As a compromise, to keep the Wiuf & Hein type layout, we could do something like this, perhaps?

<img width="374" alt="Screenshot 2022-02-15 at 12 33 27" src="https://user-images.githubusercontent.com/4699014/154062885-a66c02c8-7826-4418-a2e1-f746d0393a40.png">

**Comment by hyanwong** [comment]
> What if we use code-generated figure here instead of hand-built one then? Shouldn't be too hard to add the edge annotations?

Yes, we could do that. Do we want the internal genomes (inside the nodes) added too?

**Comment by hyanwong** [comment]
If we group the recombining nodes together, it becomes a little more recognisable as the W&H graph, without having to do weird right angles on the edges:
<img width="359" alt="Screenshot 2022-02-15 at 14 27 41" src="https://user-images.githubusercontent.com/4699014/154081887-47cef1cc-93c8-4d98-8618-4468823157b3.png">

**Comment by hyanwong** [comment]
Here are the intervals (networkx default edge labelling). Perhaps we should have them all horizontal, rather than rotated. It would be less busy if we had a symbol for `(0,7]`. Or instead of labels, we could simply show a filled bar showing the extent of genome transmitted?

<img width="481" alt="Screenshot 2022-02-15 at 14 56 08" src="https://user-images.githubusercontent.com/4699014/154087465-a5c55e61-4dad-413e-84d9-aa4ef54afa1b.png">

**Comment by hyanwong** [comment]
<img width="294" alt="Screenshot 2022-02-15 at 15 17 44" src="https://user-images.githubusercontent.com/4699014/154091653-2508ac44-da54-42be-bcbb-879df83e2e01.png">

**Comment by jeromekelleher** [comment]
The last one looks great. What are you thinking then for the other pictures where we show the fully resolved ancestry?

**Comment by a-ignatieva** [comment]
I'd avoid making the edges arrows - I think this could confuse things as "explicit" ARGs like the one in the right panel commonly have arrows as edges pointing down (not up). Could add a big arrow next to the two args though, pointing up or down, to emphasise the directionality?

Also - do we not want genomes on the nodes? Not wedded to the idea, just thought this made it easy to get the message at a glance.

**Comment by hyanwong** [comment]
> The last one looks great. What are you thinking then for the other picture where we show the fully resolved ancestry?

I guess we show all the intervals on all the edges?

Also we will (presumably) use line thickness or greyscale to show the amount passing through each, which will be quite different in (a) and (b). Just waiting for Wilder to fix the few remaining things in #85 

> Also - do we not want genomes on the nodes? Not wedded to the idea, just thought this made it easy to get the message at a glance.

I can try adding those later, but it's a bit more fiddly.

**Comment by hyanwong** [comment]
Here it is with arrows, although I saw @a-ignatieva isn't keen:

![image](https://user-images.githubusercontent.com/4699014/154107825-dbe29b71-60d9-42fa-aa77-eaed574a1fe7.png)

I don't think arrows make sense on the implicit one. There's no directionality here

**Comment by jeromekelleher** [comment]
I don't think it's a good idea to omit some edge annotations -- this is just going to make people think that we have two different types of edges (recombination or not) or something. We want to emphasise that an edge is an edge, and they're all treated equally.

So, I'd vote for adding in all the values.

Re arrows, I think we should have them in both or neither. It think it does help to clarify what's going on if you put the arrows in the left hand one: this is what child inherits from parent. The other way around, this is what propagates up to the parent from child.

I'm not sure there's much value in the "implicit" vs "explicit" terminology now either - I think the forwards-time vs backwards-time perspective is much more useful.

**Comment by jeromekelleher** [comment]
(But, looks great!)

**Comment by hyanwong** [comment]
> But I don't think of the left hand one as forward time in any way. It is time agnostic, I think?

More precisely, for example, L passes on (0,3] to N, or alternatively, N inherits (0,3] from L. It's entirely symmetrical, isn't it?

**Comment by hyanwong** [comment]
> > I'm not sure there's much value in the "implicit" vs "explicit" terminology now either - I think the forwards-time vs backwards-time perspective is much more useful.
> 
> But I don't think of the left hand one as forward time in any way. It is time agnostic, I think?

Case in point: you can simulate the Griffiths graph backwards in time, encoding it as per the edges in figure (a): that's what `argutils.sim_coalescent` and `argutils.sim_wright_fisher` do, right? That's a backwards-time perspective, just not using the Hudson algorithm.

**Comment by jeromekelleher** [comment]
> More precisely, for example, L passes on (0,3] to K, or alternatively, K passes up (0,3] to L. It's entirely symmetrical in both time directions, isn't it? As long as you are working completely locally, that is (i.e. without reference to the samples)

Think about it this way. R passes on [0, 7) to child G. This is just the forwards-time generation-by-generation inheritance of a chromosome segment. However, G passes ancestral material  (2, 7] **with respect to the samples** to R. The latter is intrinsically backwards in time, and must be with respect to some set of samples.  When thinking about R to G though, I think it's most helpful to think about it as parent passes-something-to-child. Since backwards-time processes only make sense wrt to a given sample, it's better not to think about it locally. 

Do you see what I mean? I'm not saying that this is the only way to look at it, I just think it's the most helpful.

**Comment by jeromekelleher** [comment]
Another related thought: the graph *is* directed. We must think of the edges (u,v) as being ordered, or we'll get loops. We can either think of the edges being directed backwards in time, or forwards in time. Both make sense, but it must be one or the other. Since there is no concept of samples in panel (A) I think it's best to think of edges as pointing downwards. This makes it easy to explain why the annotations are the way they are: we think of it as precisely the segment of genome that parent passed to child. If you had to choose a direction in which that happened in, it's from parent to child. Ancestral material is different, that percolates up the graph, from child to parent.

Yet another thought: since samples really are special in (B) and they are important to understanding what's going on here, maybe we should be highlighting them?

**Comment by hyanwong** [comment]
But plot (a) is defined wrt samples! Otherwise we would have a load more genomes in there, that do not make it to time 0.

**Comment by hyanwong** [comment]
It's the tracing of material that goes back form the samples in (b). I really do think that the forwards time thing is a red herring. It's "local" vs "nonlocal (backwards form the samples)", I'm convinced of it.

**Comment by hyanwong** [comment]
Here are the edge colour/width equivalents. I've put the intervals on the full edges, but I do feel that makes it quite hard to see what's going on in (a), and would like somehow to de-emphasize the intervals on the full edges, somehow. Any suggestions?

Intensity

![image](https://user-images.githubusercontent.com/4699014/154139729-f726eb6c-60a1-4122-b7af-b9321cc56274.png)

Width

![image](https://user-images.githubusercontent.com/4699014/154139862-3db99923-d748-4a17-9d1e-3ea8b4a3dfbb.png)

**Comment by hyanwong** [comment]
Here are the equivalent trees:

<img width="1013" alt="Screenshot 2022-02-15 at 21 31 11" src="https://user-images.githubusercontent.com/4699014/154152665-b3401d5a-d7bf-4978-8dfb-bf3c741adad6.png">

<img width="977" alt="Screenshot 2022-02-15 at 21 30 41" src="https://user-images.githubusercontent.com/4699014/154152591-d38975a8-9f8c-4f9f-97d7-0dadacdb03c0.png">

**Comment by jeromekelleher** [comment]
> But plot (a) is defined wrt samples! Otherwise we would have a load more genomes in there, that do not make it to the samples, but end up elsewhere (or don't even make it to time 0).

I'm not talking about the process here, just the graph as given. So, given the graph, what's the best way to interpret the edge (u, v) between a child and a parent. All I'm saying is that in (a) this is most simply thought of as the **parent** transmitting its genetic material to the **child** (with no reference to the set of samples), and in (b) this is best thought of as the child transmitting ancestral material relative to the sample, to the parent. I probably confused this by talking about forwards-time vs backwards-time,  apologies.

Anyway, this wouldn't look good with arrows in any case, so lets just drop it.

**Comment by jeromekelleher** [comment]
Some suggestions

- I don't think it's helpful showing edge weights in (a), I think it would be better to just show lines like before (so, every edge looks the same). There's no real information in the weights here, I think.
- I agree the intervals are quite hard to spot in (a) now. Like you say, how about we show all of them, but emphasise the ones for recombinations? So, show the edge label on  e.g. A-H in light grey or something? 
- The trees in (b) look really nice, and are perhaps helpful to people? I wonder if (a) would confuse people - you only get this topology with hanging branches if you build the tree from the root down. If you work up from the leaves, you get the same topologies as (b). This would take some explaining, and I don't want to have to talk about building trees top-down (I'm explaining the leaf-up version in #109).
- But, on the other hand the trees don't have anything to do with the point of the figure, so maybe that's just a distraction?

**Comment by hyanwong** [comment]
>All I'm saying is that in (a) this is most simply thought of as the **parent** transmitting its genetic material to the **child** (with no reference to the set of samples), and in (b) this is best thought of as the child transmitting ancestral material relative to the sample, to the parent.

Yes, I agree with this. There is a small difference in that in (b) the material "thins out" as you go up, but in (a) it doesn't thin as you go down.

> I probably confused this by talking about forwards-time vs backwards-time, apologies.

Yep, I think we need to be a bit careful here, and talk about transmission direction.

> Anyway, this wouldn't look good with arrows in any case, so lets just drop it.

SGTM

> * I don't think it's helpful showing edge weights in (a), I think it would be better to just show lines like before (so, every edge looks the same). There's no real information in the weights here, I think.
> * I agree the intervals are quite hard to spot in (a) now. Like you say, how about we show all of them, but emphasise the ones for recombinations? So, show the edge label on e.g. A-H in light grey or something?

I think these two are linked. If it's obvious which are full intervals, we probably don't need the weights.

> * The trees in (b) look really nice, and are perhaps helpful to people? I wonder if (a) would confuse people - you only get this topology with hanging branches if you build the tree from the root down.

The hanging branches are an interesting take on the situation, and ISTR that you found this a helpful insight (because of comparison to the ancestors TS in tsinfer, I think), but maybe it's a step too far for the average reader?

> * But, on the other hand the trees don't have anything to do with the point of the figure, so maybe that's just a distraction?

This seemed like the best place to describe the hanging branches thing, if we wanted to. Perhaps we could stick the tree views in a supplementary?

**Comment by jeromekelleher** [comment]
> The hanging branches are an interesting take on the situation, and ISTR that you found this a helpful insight (because of comparison to the ancestors TS in tsinfer, I think), but maybe it's a step too far for the average reader?

It's hard to know - it helped me because I spent so long staring at trees like this when developing tsinfer. They are probably not as obvious to other people. It does depend on how to build the trees too, so perhaps it's just a diversion.

**Comment by hyanwong** [comment]
> perhaps it's just a diversion.

I am in favour of having some illustrations like this in a small supplement.

**Comment by a-ignatieva** [comment]
I think this looks great! Don't suppose there's a way to make the labels by DEB and LMK and TUS not overlap the edges?

I think there's a way of making networkx add pictures on the nodes. Could I have a go at adding genomes onto the graph this way? Just to see if it looks better or worse through being too busy.

**Comment by hyanwong** [comment]
> I think this looks great! Don't suppose there's a way to make the labels by DEB and LMK and TUS not overlap the edges?

I'm sure there is. I don't mind them on the edges generally, but ISWYM when you can't see any edge.
> 
> I think there's a way of making networkx add pictures on the nodes. Could I have a go at adding genomes onto the graph this way? Just to see if it looks better or worse through being too busy.

That would be great. Shall I PR, merge, then you can make changes?

**Comment by hyanwong** [comment]
OK, merged: https://github.com/tskit-dev/what-is-an-arg-paper/pull/114

Go wild, @a-ignatieva !

**Comment by hyanwong** [comment]
If you don't want to use networkx directly, @a-ignatieva, you can get the positions out and overlay SVGs onto this plot, but that's probably more complex and fragile than getting networkx to do it.

**Comment by jeromekelleher** [comment]
I think we can probably close this issue now, and raise other more specific ones if we want to disuss?
