### ISSUE TITLE
Layout nodes by time in viz

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#65]
The current ``argutils.draw()`` method produces slightly odd layouts in the y direction. See here for example:

![wh99](https://user-images.githubusercontent.com/2664569/152805107-bed4d497-57cf-474d-a295-913dc3ffd4b3.png)

It would be nice to be able to layout the nodes in time-rank order so that here nodes 3 and 4 (which have the same time) are at the same level, but different to all the others.

@hyanwong - is this possible with the dot layout used for the x layout (which is great)?

**Comment by hyanwong** [comment]
There is supposedly a way to do it in dot, but I've never got it to work satisfactorily. There's a comment where we say "# First cluster all nodes at the same times (probably mostly samples)". OTOH we do change the Y coords from the dot layout after the fact. Let me see what I can do.

**Comment by jeromekelleher** [comment]
The ``pos = nx.multipartite_layout(G, subset_key="time", align="horizontal") `` does a good job of laying out by time for pedigrees.

**Comment by hyanwong** [comment]
The nx layouts don't try to minimise line crossing at all, which is why I had to use dot. We could then use the Y positions from the multipartite layout, I suppose.

**Comment by hyanwong** [comment]
Just had a look. That's what the "add invisibles" thing does. Shall I expose it in the `draw` function?

It doesn't always work as expected, which is why I didn't turn it on be default. The resulting plot does weird stuff in the X direction now:

![Screenshot 2022-02-08 at 09 41 17](https://user-images.githubusercontent.com/4699014/152960141-3c29c4d1-e29c-4342-b36e-f19634c3d07c.png)

**Comment by jeromekelleher** [comment]
That does look worse layout wise now. I think it'd probably be simpler to do the y layout ourselves - what we want is straightforward isn't it?

**Comment by hyanwong** [comment]
Yep, I think we just impose the ranks onto the Y axis ourselves.

**Comment by hyanwong** [comment]
![Screenshot 2022-02-08 at 10 12 10](https://user-images.githubusercontent.com/4699014/152966179-6943e649-7d93-4e13-85eb-c817ba73bf72.png)

Using

```
def draw(ts, ax, use_ranked_times=None):
    """
    If use_ranked times is True, the y axis uses the time ranks, with the
    same times sharing a rank. If False, it uses the true (tree sequence)
    times. If None, times from the tree sequence are not used and the
    standard dot layout is used
    """
    G = convert_nx(ts)
    labels = {j: f"{j}" for j in range(ts.num_nodes)}
    pos = nx_get_dot_pos(G)
    if use_ranked_times is not None:
        if use_ranked_times:
            _, inv = np.unique(ts.tables.nodes.time, return_inverse=True)
            ranked_times = (np.cumsum(np.bincount(inv)) - 1)[inv]
            for i, p in pos.items():
                p[1] = ranked_times[i]
        else:
            times = ts.tables.nodes.time
            for i, p in pos.items():
                p[1] = times[i]
    nx.draw(
        G,
        pos,
        # node_color=colour_map,
        node_shape="o",
        node_size=200,
        font_size=9,
        labels=labels,
        ax=ax,
    )
```

**Comment by hyanwong** [comment]
I think we want the ability to tweak the X position of certain points (e.g. 0 here)
