### ISSUE TITLE
Graph viz layout seemingly non-deterministic

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#75]
Weirdly, when I run the following code after restarting the notebook kernel, I get slightly different X layouts. This is *really* annoying. It seems like the dot layout engine should be deterministic, so I don't know what's going on here.

```
ts = argutils.sim_coalescent(4, 0.001, 1000, seed=123)
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1) = plt.subplots(1, 1, figsize=(10,10))
argutils.viz.draw(ts, ax1, use_ranked_times=True)
```

1st attempt
![image](https://user-images.githubusercontent.com/4699014/153031415-39a23221-d559-42a4-b646-54077701630d.png)

repeat attempt
![image](https://user-images.githubusercontent.com/4699014/153031459-b7687c10-0be9-4cc3-8c6f-00256dae4c4a.png)

**Comment by jeromekelleher** [comment]
That is very irritating. Do we know what the underlying calls to graphviz are? We could do a bit of digging then.

**Comment by hyanwong** [comment]
Looks like the returned values from `A.get_node(n).attr["pos"]` are indeed different:

```
1st iteration      2nd iteration
node 0: 301,738    node 0: 193,738 
node 1: 85,738     node 1: 121,738 
node 2: 229,738    node 2: 337,738 
node 3: 157,738    node 3: 265,738 
node 4: 130,522    node 4: 115,666 
node 5: 58,522     node 5: 43,666  
node 6: 197,666    node 6: 337,666 
node 7: 91,450     node 7: 79,594  
node 8: 352,666    node 8: 265,666 
node 9: 280,666    node 9: 193,666 
node 10: 331,59    node 10: 195,5944
node 11: 259,59    node 11: 267,5944
node 12: 187,59    node 12: 339,5944
node 13: 259,52    node 13: 267,5222
node 14: 211,45    node 14: 272,4500
node 15: 43,378    node 15: 53,378 
node 16: 115,37    node 16: 125,3788
node 17: 265,37    node 17: 275,3788
node 18: 193,37    node 18: 203,3788
node 19: 187,30    node 19: 197,3066
node 20: 187,23    node 20: 197,2344
node 21: 187,16    node 21: 197,1622
node 22: 115,16    node 22: 125,1622
node 23: 115,90    node 23: 125,90 
node 24: 142,18    node 24: 152,18 
```

**Comment by hyanwong** [comment]
Could be this: https://forum.graphviz.org/t/clustering-gives-undeterministic-results/989

**Comment by hyanwong** [comment]
It seems as if using pydot rather than pygraphviz makes this deterministic (possibly because it calls the C libs directly). I just have to figure out how to get the positions out of pydot.
