### ISSUE TITLE
Figure 5: Which nodes are optional in an edge-annotated arg

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#82]
Here's what we have at the moment
<img width="566" alt="Screenshot 2022-02-09 at 14 50 09" src="https://user-images.githubusercontent.com/4699014/153225761-6a8b4ade-4cb1-4e5e-923b-034ea0e282ca.png">

but we want to replace this with an arg simulated using the `argutils.sim_coalescent` method. I suggest using the one below (from [here](https://github.com/tskit-dev/what-is-an-arg-paper/issues/80)). We need to think about what node colour we use, including representing the length over which a node is coalescent as a shade of colour. We should also think what we say about the pass-through nodes (these are mostly the 2 parents that exist for each recombinant node). In the plot above we get rid of these by showing a MultiDiGraph, where e.g. a diamond can be shown by two edges joining a parent to a child node.

```
import argutils
import matplotlib.pyplot as plt
import tskit
ts = argutils.viz.label_nodes(argutils.sim_coalescent(4, 0.001, 1000, seed=123))
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(20,10))
ax1.set_title("(a) full coalescent arg")
ax2.set_title("(b) simplified keeping unary in coal")
ax3.set_title("(c) fully simplified")
pos = argutils.viz.draw(ts, ax1, use_ranked_times=True, tweak_x={24: -15, 23: -5, 22: -10, 21: -10})
new_ts, node_map = simplify_keeping_unary_in_coal(ts, map_nodes=True)
argutils.viz.draw(new_ts, ax2, pos={node_map[i]: p for i, p in pos.items()})
new_ts, node_map = ts.simplify(map_nodes=True)
argutils.viz.draw(new_ts, ax3, pos={node_map[i]: p for i, p in pos.items()})
```

![image](https://user-images.githubusercontent.com/4699014/153241204-1fdc672b-2566-4f13-ad54-3c5023004fb7.png)<img width="736" alt="Screenshot 2022-02-09 at 15 05 38" src="https://user-images.githubusercontent.com/4699014/153228679-50b14c86-f716-49d3-bc04-77b51e7c7661.png">

WRT pass though nodes, I note that in the Griffiths implicit "event" encoding, we would (I think) replace each triplet of nodes (a recombinant and its 2 parents, e.g. {A,I,J} or {U, V, W}) with a single event, plus an annotation about the breakpoint, and a specification about which edge corresponds to which section of the genome.

**Comment by hyanwong** [comment]
There's an intermediate stage of simplification between plots (a) and (b) above, where we remove the pass through nodes but keep the recombination and/or coalescent nodes.

**Comment by jeromekelleher** [comment]
Maybe we should use a WF simulation as an example? We're not making the point elsewhere that something can be a recombinant and a coalescence, so good to illustrate here? Everything else is using the coalescent.

**Comment by hyanwong** [comment]
We could do, but then we get bazillions of nodes, since nearly every node ends up being a recombinant node. For example, below is what we get for `argutils.sim_wright_fisher(4, 10, 4, seed=123)` which is only 3 bases long and in a population of size 10(!). Note that the plot above has nodes that are both recombinants and coalescence nodes though?

```
import argutils
import matplotlib.pyplot as plt
import tskit
ts = argutils.viz.label_nodes(argutils.sim_wright_fisher(4, 10, 4, seed=123))
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(20,10))
ax1.set_title("(a) full coalescent arg")
ax2.set_title("(b) simplified keeping unary in coal")
ax3.set_title("(c) fully simplified")
pos = argutils.viz.draw(ts, ax1, use_ranked_times=True, tweak_x={24: -15, 23: -5, 22: -10, 21: -10})
new_ts, node_map = argutils.simplify_keeping_unary_in_coal(ts, map_nodes=True)
argutils.viz.draw(new_ts, ax2, pos={node_map[i]: p for i, p in pos.items()})
new_ts, node_map = ts.simplify(map_nodes=True)
_= argutils.viz.draw(new_ts, ax3, pos={node_map[i]: p for i, p in pos.items()})
```

![image](https://user-images.githubusercontent.com/4699014/153260253-2b1bc95d-6e8b-4a36-9137-bb714ec997bf.png)


(NB - I had to hack the `simplify_keeping_unary_in_coal` function to delete the individuals that the WF sim places in)

**Comment by jeromekelleher** [comment]
Interesting.. so the issue is that we're recombining too much I guess? We could add a recombination rate argument instead of having a mandatory split each generation. 

I do like the complicated stuff we're getting with ACEF...

**Comment by hyanwong** [comment]
> We could add a recombination rate argument instead of having a mandatory split each generation.

Ah yes, of course. This is like we are simulating the entire length of a chromosome each generation. A rate argument would indeed be good.

> I do like the complicated stuff we're getting with ACEF...

Yes, I agree. I think I dismissed this too readily.

**Comment by hyanwong** [comment]
Here's a WF example. I thought, however, that every recombination node should have 2 parents at equal times, which isn't true for node P. Also, I'm not sure why all the sample nodes have single pass-through nodes above them. Any ideas why @jeromekelleher: there's something I'm not understanding here.

```
import sys
sys.path.append("..") # Adds higher directory to python modules path.

import argutils
import matplotlib.pyplot as plt
import tskit
ts = argutils.viz.label_nodes(argutils.sim_wright_fisher(2, 10, 100, recomb_proba=0.1, seed=10))
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(20,10))
ax1.set_title("(a) full coalescent arg")
ax2.set_title("(b) simplified keeping unary in coal")
ax3.set_title("(c) fully simplified")
pos = argutils.viz.draw(ts, ax1, tweak_x={24: 10, 25: 20, 26:-15, 27: -10, }, use_ranked_times=True)
new_ts, node_map = argutils.simplify_keeping_unary_in_coal(ts, map_nodes=True)
argutils.viz.draw(new_ts, ax2, pos={node_map[i]: p for i, p in pos.items()})
new_ts, node_map = ts.simplify(map_nodes=True)
_= argutils.viz.draw(new_ts, ax3, pos={node_map[i]: p for i, p in pos.items()})
```

![image](https://user-images.githubusercontent.com/4699014/153569204-fe27e9dc-7dfd-49f4-8131-210fd07bdbd8.png)

**Comment by jeromekelleher** [comment]
There's something wrong with the simulator there - the edges B-E etc shouldn't be there.

**Comment by jeromekelleher** [comment]
LMK if you want me to fix it

**Comment by hyanwong** [comment]
Thanks @jeromekelleher - if it's an easy fix, please do. I haven't looked at how the code works, so you'll be a lot quicker doing it than me.

**Comment by jeromekelleher** [comment]
Will do

**Comment by hyanwong** [comment]
We had discussed using the Wiuf & Hein HUD ARG for this example (see 2 possible versions at https://github.com/tskit-dev/what-is-an-arg-paper/pull/95 ) but it is missing two features which might be nice to show: firstly, we thought of using this as an example of a big arg, so we could see the removal of non-ancestral nodes on simplification. But it isn't a biog arg, it's the little ARG. Secondly, we thought, if we show the 2-RE-node version, we could demonstrate 2 gametes from the same parent in the graph (i.e. one of the RE nodes is also a CA node). 

So I wonder if we do actually want to use a WF example instead of Wiuf & Hein?

**Comment by hyanwong** [comment]
Here's that WF example with the new code. I assume that the cases where there is a recombinant node with only 1 node above it (e.g. node L) it is because the other node did not have any ancestral material.

![image](https://user-images.githubusercontent.com/4699014/153747809-fca30521-d563-4e4d-976d-8ca4ece9a894.png)

**Comment by hyanwong** [comment]
> Looks to me like L has two parents, O and P? Maybe it's the y coordinates here are a little off?

I don't think it can be that, because O and P can't be at the same time (they are joined by an edge), and this presumably doesn't have overlapping generations. So I'm a bit puzzled here.

**Comment by hyanwong** [comment]
I was also hoping to find an example where two samples shared (one of) the same parents. I'll have a look.

**Comment by jeromekelleher** [comment]
> I don't think it can be that, because O and P can't be at the same time (they are joined by an edge), and this presumably doesn't have overlapping generations. So I'm a bit puzzled here.

Ah yes, true!

**Comment by hyanwong** [comment]
Here's a nice example. It has multiple roots, 2 collapsed recombination events (onto node B), a clear diamond, a node that is both a coalescent node and the parent ofd a recombinant, and a good reason to keep_unary_in_coal. Additionally, if we reverse the X axis, the nodes are in the same order as the marginal trees plot. I'm strongly inclined to use this in the example. OK?

```
ts = argutils.viz.label_nodes(argutils.sim_wright_fisher(2, 10, 100, recomb_proba=0.1, seed=354))

print(f"Seed {seed}: {ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(20,10))
ax1.set_title("(a) full coalescent arg")
ax2.set_title("(b) simplified keeping unary in coal")
ax3.set_title("(c) fully simplified")
pos = argutils.viz.draw(ts, ax1, use_ranked_times=True, tweak_x={15: 14, 12: 11, 11:-10})
new_ts, node_map = argutils.simplify_keeping_unary_in_coal(ts, map_nodes=True)
argutils.viz.draw(new_ts, ax2, pos={node_map[i]: p for i, p in pos.items()})
new_ts, node_map = ts.simplify(map_nodes=True)
_= argutils.viz.draw(new_ts, ax3, pos={node_map[i]: p for i, p in pos.items()})
```


![image](https://user-images.githubusercontent.com/4699014/153900890-c33b6f3b-03c9-4c98-bd9d-ee92de0a8368.png)

![image](https://user-images.githubusercontent.com/4699014/153900944-6ba41788-ef39-444a-875c-e3c34f1679c6.png)

**Comment by jeromekelleher** [comment]
I like it, let's get it in!

**Comment by hyanwong** [comment]
Closed with https://github.com/tskit-dev/what-is-an-arg-paper/pull/110. Let's open new issues if any changes are needed.
