### ISSUE TITLE
Tweaks to Figure 2: Encoding an ARG: Griffiths (node annotated w/ events) vs TS (edge annotated w/genomes)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/what-is-an-arg-paper#90]
https://github.com/tskit-dev/what-is-an-arg-paper/pull/89 incorporated a draft plot and caption for Fig 2: Encoding an ARG. This issue is to collect ideas for possible tweaks or improvements to the figure. It can be closed once we the figure is out of "draft" form.

**Comment by jeromekelleher** [comment]
![argds](https://user-images.githubusercontent.com/2664569/153582804-5457b785-2a8e-4324-a88b-c2140a3fa75d.png)

**Comment by hyanwong** [comment]
A few comments I made previously: I suggest that we consider removing the infinity signs in the LH table, and just have blanks, `NA` or `-` to indicate that the idea of a breakpoint is not applicable to those nodes. I also think it might be worth  distinguishing the node numbers when they refer to an *event* and when they refer to a *genome*, perhaps by italics, bold, or sans serif font for the node ID numbers?

**Comment by jeromekelleher** [comment]
> actually, do we even need the LH table? The information is on the plot, apart from the order information, which is not in the table either)

We do - the point is to explicitly show all the information that we need to store. The diagram is there to illustrate the encoding, not the other way around.

**Comment by hyanwong** [comment]
> We do - the point is to explicitly show all the information that we need to store. The diagram is there to illustrate the encoding, not the other way around.

A fair point, but 

(a) we don't need to store lots of NAs: I think it would be more obvious to people to store the recombination node number and a breakpoint, rather than a table of all nodes (including non-recombination ones) and 

(b) we aren't showing all the information we need: we also need to store the order of parents at each breakpoint. True, this is implicit in the table list you show, because of the order, but I think that's a rather complex way to store it?

It would be more obvious (to me, at least) to show something like

```
node_id breakpoint L_parent R_parent
3         x           4         5
```

**Comment by jeromekelleher** [comment]
I'm trying to do this in a mathematical way - let's wait until the text is written before going into this please.

**Comment by hyanwong** [comment]
I see the mathematical bit of text goes like this (I think), @jeromekelleher 

```
Each recombination event is associated with a breakpoint 0 < x < L, 173 which we might encode as a mapping f : N → {0, ..., L − 1} such that f (u) is the recombination 174 breakpoint if u is a recombination node and f(u) = ∞ otherwise.
```

I find the mapping stuff (which is what you allude to in the figure caption) pretty confusing. Would it perhaps be simpler to say that the nodes are of different classes. For example, we could say that there a Griffiths ARG consists of N nodes, where nodes 1..R are recombination nodes, and nodes R+1..N are CA nodes. The function then simply maps 1..R -> breakpoint numbers, and we don't need to worry about the infinity stuff, which is simply a flag for the idea that there is no breakpoint associated with a CA node. Perhaps @JereKoskela has a suggestion for a more mathematical formulation than my suggestion here, though?

**Comment by JereKoskela** [comment]
I think introducing a dependency on node ordering adds more complication than it removes. I don't think that ∞ is ideal for a null symbol; it makes me expect that we'll want to do something like evaluate `exp(-f(u))` at some point and have it equal 0 for coalescence nodes. I'd prefer `NA` or `NULL`, or `Δ`, which is a common cemetery state symbol in stochastic processes, to emphasize that this really is just a flag for blankness. But apart from that cosmetic tweak (which isn't very important), I like what we have currently.

**Comment by hyanwong** [comment]
>  I'd prefer `NA` or `NULL`, or `Δ`, which is a common cemetery state symbol in stochastic processes, to emphasize that this really is just a flag for blankness. 

SGTM. The other possibility, without introducing a dependency on order, is to say that we explicitly have 2 types of nodes (they could even be numbered independently). Then we could point out that the ts formulation collapses that down into a single node type, the genome. I think this is perhaps what we are arguing for in the paper?

**Comment by jeromekelleher** [comment]
Having two types of node is the same thing as saying there's a function f(u) which returns a breakpoint if it's a recombination and something else otherwise. I really can't see a more economical way of saying this: you need an ordered list of edges [(u, v)] and a function f(u) mapping node IDs to breakpoints (or null).

If you have two types of node like you suggest, then you can't used edges of the form (integer, integer).

We're not talking about describing a file format or anything here, this is about mathematical simplicity.

I don't have any particular attachment showing infinities as the null value.

**Comment by hyanwong** [comment]
> Having two types of node is the same thing as saying there's a function f(u) which returns a breakpoint if it's a recombination and something else otherwise. 

Yes, I know it is to *us*, but I suspect that might be a confusing way of putting it to the reader, that's all. My guess is that the normal reader would assume a table of recombination nodes, with breakpoints, and a table of common ancestor nodes, without. But I'm not a normal reader, so I could be completely off here.

> I really can't see a more economical way of saying this: you need an ordered list of edges [(u, v)] and a function f(u) mapping node IDs to breakpoints (or null).

TBH I've never thought of it as a (mathematical) function before, simply as an indexed set of numbers. Perhaps that's why I found the phrasing interrupted my reading of the text?

**Comment by hyanwong** [comment]
> If you have two types of node like you suggest, then you can't used edges of the form (integer, integer).

Yes, this is a very good point. How does Griffiths define it, I wonder. I'll go and look.

**Comment by jeromekelleher** [comment]
We can assume a degree of mathematical sophistication in our core audience.

You won't find any proper definitions of the *data structure* in Griffiths (or anywhere else, AFAIK). It's all very wooly.

**Comment by hyanwong** [comment]
Do we want to use the matplotlib / networkx functions to draw the ARG in this figure? It would perhaps make an easier lead in to the rest of the graph-like figures in the paper (e.g. fig 4).

Also, we should probably have the V-shaped recombination node in (B), and explain that the time of the recombination is stored in the upper 2 nodes.

Might it also be useful to say somewhere that the 2-node encoding means that diamonds can be encoded without relying on a MultiDiGraph?

**Comment by hyanwong** [comment]
> should we have a V-shaped edge layout between nodes 3, 1, 4 in (B), 

Or perhaps we should show a "divided T" shape, as in https://github.com/tskit-dev/what-is-an-arg-paper/issues/56#issuecomment-1040220303 and reproduced below:

<img width="374" alt="Screenshot 2022-02-15 at 12 33 27" src="https://user-images.githubusercontent.com/4699014/154062885-a66c02c8-7826-4418-a2e1-f746d0393a40.png">

**Comment by jeromekelleher** [comment]
I think it's more important that we have continuity with the literature at this point - I want the reader to look at Figure a and say "yes, that's an ARG diagram like I'm used to", and see (b) and say "that's basically the same". This is critical.

Time is actually never really mentioned in ARG stuff, so I think we can just leave it out, beyond the mention of needing a t(u) function if we want time resolved ARGs.

**Comment by hyanwong** [comment]
> I think it's more important that we have continuity with the literature at this point - I want the reader to look at Figure a and say "yes, that's an ARG diagram like I'm used to", and see (b) and say "that's basically the same". This is critical.

Yes, on reflection I agree 100%. But I do wonder what it means to have this:
 
<img width="74" alt="Screenshot 2022-02-17 at 08 32 16" src="https://user-images.githubusercontent.com/4699014/154436404-b5dc17fa-910f-4728-9ee2-84273a69d578.png">

Without a node at the joining point of the lines. That's not really an acceptable (mathematical) graph, is it? Unless there is an unlabelled node at that point too.

> Time is actually never really mentioned in ARG stuff, so I think we can just leave it out, beyond the mention of needing a t(u) function if we want time resolved ARGs.

Good point.

**Comment by jeromekelleher** [comment]
I think people will understand that the vertical parts of the edges are overlaid, but we can try a split T if you like. It's a minor detail, let's worry about it in the final stages.

**Comment by hyanwong** [comment]
> I think people will understand that the vertical parts of the edges are overlaid, 

Oh, they are *overlaid* are they? That's not what I understood! I thought they merged. Perhaps I was being dense.

> but we can try a split T if you like. It's a minor detail, let's worry about it in the final stages.

Yep.

**Comment by jeromekelleher** [comment]
> Oh, they are overlaid are they?

Yes - I thought that was obvious. It's just how the edges are drawn - that's why we have the little node circles.

**Comment by hyanwong** [comment]
> > Oh, they are overlaid are they?
> 
> Yes - I thought that was obvious. It's just how the edges are drawn - that's why we have the little node circles.

I can see that now that you say it, but it wasn't obvious to me when (naively) looking at the diagram itself.

**Comment by jeromekelleher** [comment]
Lets try this version for a bit then, see if we like it:

![shoulders](https://user-images.githubusercontent.com/2664569/154497979-7c716a47-08dc-40b2-bf83-e607cc2a00c2.png)

**Comment by hyanwong** [comment]
Obsoleted by https://github.com/tskit-dev/what-is-an-arg-paper/pull/134 I think
